[호돌] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #1
Opened 2020-06-03 06:58 UTC by woonjangahn

[여기](https://github.com/woonjangahn/woowa-userstory-2020/blob/woonjangahn/README.md)를 참고하세요!🚀

2020-06-05 03:50 UTC, KueNiYam approved these changes
안녕하세요, 호돌! 그니입니다. :)

최근에 PPT를 작성하며 마크다운으로 작성할 수 있었으면 좋겠다라는 생각을 했어서 인상 깊네요. :)
또한, 스마트폰을 리모콘으로 사용한다는 생각도 좋은 것 같아요.!
제 생각으로는 통신을 블루투스가 아닌 서버를 통해서 할 것 같은데, 발표 기기에서 블루투스를 지원하지 않아도 사용 가능하다는 점이 좋아요.

다만, 고려해야할 부분은 생각 외로 마크다운 문법을 아는 사용자가 적다는 것이 있을 것 같아요. 
이 부분을 조금만 더 고려한다면 굉장히 좋은 기획안이 될 것 같습니다..!

2020-06-06 05:44 UTC, KS-KIM approved these changes
안녕하세요 호돌🐯, 알트입니다! 미션 잘 작성하셨네요 👍👍

마크다운을 선호하는 저같은 개발자들에게 좋은 서비스가 될 것 같아요.
특히, 스마트폰을 이용한 리모컨 모드는 꼭 써보고 싶어요!
추가적인 아이디어를 제안하자면, [slides](https://help.slides.com/knowledgebase/articles/333924-present-view-live-streaming)라는 PPT 서비스처럼 현재 진행중인 강의자의 슬라이드를 각 청중의 노트북에서 볼 수 있는 기능이 추가되었으면 좋겠습니다.

맞춤법 피드백은 확인해보시고 고칠 필요성을 느끼시면 반영해주세요.
고생하셨습니다! 이만 Approve 할게요😊

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +  - **리모콘 모드 -** 스마트폰으로 리모콘 모드로 진입하여 PPT를 조작한다.
```suggestion
  - **리모컨 모드 -** 스마트폰으로 리모컨 모드로 진입하여 PPT를 조작한다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +  - **대본/노트 모드** - 발표용 스크린이 아닌 본인 노트북 또는 태블릿에서 PPT 작성시 만든 페이지별 대본 또는 노트를 확인할 수 있다.
```suggestion
  - **대본/노트 모드** - 발표용 스크린이 아닌 본인 노트북 또는 태블릿에서 PPT 작성 시 만든 페이지별 대본 또는 노트를 확인할 수 있다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +  - 자료를 작성하는데 있어 제일 불편한 점은 무엇인가요?
```suggestion
  - 자료를 작성하는 데 있어 제일 불편한 점은 무엇인가요?
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 학교를 다니거나 교육을 받으며 1년에 두 번 정도 발표할 일이 있다.
```suggestion
- 학교에 다니거나 교육을 받으며 1년에 두 번 정도 발표할 일이 있다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 자주쓰는 기능만 쓴다. (도형, 채우기, 텍스트, 글씨, 정렬)
```suggestion
- 자주 쓰는 기능만 쓴다. (도형, 채우기, 텍스트, 글씨, 정렬)
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 발표 준비 기간은 주제 따라 다르지만 보통 대충 하면 3~4시간, 진지한 것은 2~3일 정도 걸리는 것 같다.
```suggestion
- 발표 준비 기간은 주제 따라 다르지만 보통 대충하면 3~4시간, 진지한 것은 2~3일 정도 걸리는 것 같다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 이미지가 많으면 PowerPoint를 사용해서 작업을 하고, 강의를 할 때는 텍스트만 사용해서 슬라이드를 만들 수 있는 NEXTSTEP 내장 에디터나 NHN Dooray를 사용한다.
```suggestion
- 이미지가 많으면 PowerPoint를 사용해서 작업하고, 강의할 때는 텍스트만 사용해서 슬라이드를 만들 수 있는 NEXTSTEP 내장 에디터나 NHN Dooray를 사용한다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- Dooray는 사용하며 인포그래픽을 넣기 좀 불편하고, 테마가 한정되어있다. 디자인은 강의자료를 만들 때는 신경을 별로 안쓰지만 사업계획서에서는 많이 신경 쓴다.
```suggestion
- Dooray는 사용하며 인포그래픽을 넣기 좀 불편하고, 테마가 한정되어있다. 디자인은 강의자료를 만들 때는 신경을 별로 안 쓰지만 사업계획서에서는 많이 신경 쓴다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 스크립트를 외우진 않고, 머리속에 슬라이드별 키워드를 대충 생각해두며 발표한다.
```suggestion
- 스크립트를 외우진 않고, 머릿속에 슬라이드별 키워드를 대충 생각해두며 발표한다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 이미지 구글링을 하지만 출처 표기같은건 신경 쓰기 어려운 것 같다.
```suggestion
- 이미지 구글링을 하지만 출처 표기 같은 건 신경 쓰기 어려운 것 같다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 자료준비까지 하면 2~3주 정도인데, 발표 준비만 1주일은 보통 걸린다.
```suggestion
- 자료 준비까지 하면 2~3주 정도인데, 발표 준비만 1주일은 보통 걸린다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 깔끔한 PPT를 만들고 싶어함. 정렬 기능을 많이 사용함.
```suggestion
- 깔끔한 PPT를 만들고 싶어 함. 정렬 기능을 많이 사용함.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 발표 시 리모콘을 쓰고 싶다.
```suggestion
- 발표 시 리모컨을 쓰고 싶다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 친구와 토이 프로젝트를 진행중인데, 지원금을 받으려고 공모전 참가 예정
```suggestion
- 친구와 토이 프로젝트를 진행 중인데, 지원금을 받으려고 공모전 참가 예정
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +  - 교육 관련 자료는 재활용하지만, 스터디 때 만드는 발표 자료는 보통 1회성.
```suggestion
  - 교육 관련 자료는 재활용하지만, 스터디 때 만드는 발표 자료는 보통 일회성.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +김경은 판교에서 퇴근 후 강남역에 있는 스터디 카페에 파이썬 원데이 클래스를 진행하러 간다. 스마트폰으로 MarkSlide에 접속해 발표자료에 날짜만 바꾸면 오늘 수업도 무사히 진행할 수 있다. 다음주 토요일 스터디 발표가 예정되어 있으니 이동 시간동안 쓸만한 이미지만 검색해서 넣어 놓는다. 슬라이드 맨 뒤에 출처가 남겨져서 구글링보다 편하다. 스터디 카
```suggestion
김경은 판교에서 퇴근 후 강남역에 있는 스터디 카페에 파이썬 원데이 클래스를 진행하러 간다. 스마트폰으로 MarkSlide에 접속해 발표자료에 날짜만 바꾸면 오늘 수업도 무사히 진행할 수 있다. 다음 주 토요일 스터디 발표가 예정되어 있으니 이동 시간 동안 쓸만한 이미지만 검색해서 넣어 놓는다. 슬라이드 맨 뒤에 출처가 남겨져서 구글링보다 편하다. 스터디 카페에 도착했다. 노트북을 연결하여 발표 모드로 바꿔놓고 스마트폰으로 슬라이드를 넘겨보며 오늘 강의를 준비한다.
```

2020-06-06 05:44 UTC, KS-KIM commented on README.md
> +- 발표모드에서 화면을 띄워주면 스마트폰으로 슬라이드를 넘길 수 있어야 한다.
```suggestion
- 발표 모드에서 화면을 띄워주면 스마트폰으로 슬라이드를 넘길 수 있어야 한다.
```

2020-06-06 07:38 UTC, lowoon approved these changes
안녕하세요, 호돌! 로운입니다.
좋은 아이디어 잘 읽었습니다. 💯 

마크 다운 방식으로 어떻게 ppt를 구현할 수 있게 할지 굉장히 기대되네요.
리모컨은 따로 준비할 필요가 없는 점과 ppt파일을 따로 준비하지 않아도 되는 점이 좋은 것 같아요.
근데 너무 개발자들을 위한 기능에만 초점이 맞추어져 있는 것 같아 노션처럼 일반 사용자들도 쉽게 사용할 수 있는 방법도 있으면 좋을 것 같습니다.

고생하셨습니다. 👍 이만 approve하겠습니다.

2020-06-08 00:22 UTC, YejiAhn approved these changes
안녕하세요, 호돌! 기획서 잘 읽어보았습니다 😊
기획 동기를 보고 서비스의 방향성이 잘 이해되는 느낌이었어요.
간단하게 발표할 일이 많은 사용자에게 정말 좋은 서비스라는 느낌을 받았는데요,
기획서에 적혀있는 내용처럼 발표 슬라이드가 만들어졌을 때 디자인적으로 *직관성과 심플함*이 잘 살아있는지가 관건이 될 것 같아요.
발표 자료를 만들 때 수많은 번거로운 작업들 없이 *아이디어에 집중*할 수 있게 해주는 서비스라면 누구나 사용하고 싶어질 것 같네요!
호돌이라면 잘 구현해내리라 믿어 의심치 않습니다.
이만 approve 할게요! 수고하셨습니다 :)

2020-06-09 05:02 UTC, Wonmi91 requested changes
안녕하세요 호돌. 워니입니다 :)
마크다운으로 PPT 작성이라니, IT 업계에서는 충분히 환영받을 수 있는 서비스인 것 같아요! 웹 기반 PPT인 것도 공유의 측면에서 편할 것 같고, 저장에 대한 부담감이 없어서 좋을 것 같네요 😊

이미지를 바로 찾아서 삽입이 가능하고, 출처가 자동으로 표기된다는 점 또한 메리트가 있는 것 같아요. 깔끔한 PPT를 원하는 사람들에게는 좋은 서비스가 될 것 같습니다.
물론 한가지 우려되는 부분이라면, 마크다운을 사용하지 않거나 익숙하지 않은 사용자들에게는 도움말 형식으로 팁을 주는 것도 좋겠어요. (사실 지금 형식이라면, 사용자 타겟이 좁혀지네요)
지금은 "PPT 만들기" 에 초점을 둔 시나리오, 기능들만 적혀 있는데요~ 웹으로 만들 수 있는 만큼 'pdf 내보내기' 혹은 '공유' 의 부분도 시나리오에 추가되면 좋겠네요!

1차 피드백 내용처럼 Nextstep에 도입될 수 있으면 좋겠어요! ㅎㅎ

2020-06-11 04:58 UTC, Wonmi91 approved these changes
피드백 반영 확인 했습니다 :)
좋은 서비스 기대할게요!
이만 merge 하겠습니다 😊

2020-06-11 04:58 UTC, merged