[범블비] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #12
Opened 2020-06-04 07:12 UTC by ddaaac

[여기](https://github.com/ddaaac/woowa-userstory-2020/blob/scenario/README.md)서 확인하실 수 있습니다. 잘 부탁드려요 :)

2020-06-05 06:45 UTC, lxxjn0 approved these changes
안녕하세요 범블비!!!

요즘 사회가 유기동물 입양을 권장하는 분위기인데 제가 보기엔 대부분 인스타그램과 같은 SNS 서비스로만 홍보가 되는 것 같아서 아쉬웠는데 이런 서비스가 있다면 정말 좋을 것 같아요.
SNS에서 제공하는 장점을 그대로 살린 서비스라고 느껴져서 많은 사람들이 사용할 수 있을 것이라는 생각이 들어요.

따로 부족한 점은 느끼지 못했지만, 서비스가 제공하는 기능이 많지는 않은 것 같아요. 부수적으로 서비스를 사용하는 사람들에게 제공하면 좋을 기능들을 생각해보는 것도 좋을 것 같습니다!!

좋은 서비스이고 이러한 서비스가 활성화되어서 문화가 좋은 방향으로 발전해나갔으면 좋겠네요.
approve 해두겠습니다 :)

2020-06-05 08:14 UTC, ghost approved these changes
제가 개발했던 '기다릴개'라는 서비스가 범블비가 기획한 서비스와 비슷하네요! 
비슷한 문제에 대해 동일한 시각을 가지고 있어서 반갑네요! :)
'기다릴개'는 웹이 아닌 앱을 통해 보호서의 동물들을 확인하고 동물 입양을 손쉽게 입양하기 위한 서비스 였는데요!
여기서 손쉽게의 의미는 유기 동물을 입양하려면 절차가 꽤나 복잡하더라구요! 그 복잡한 단계를 앱을 통해 해소해주려고 만들었는데요! 직접 방문 후 확인,서명 해야하는 서류 외에는 앱을 통해 처리할 수 있게끔 개발하였었습니다.
저희 서비스는 협력하던 동물 보호소가 문을 닫게 되어서 서비스를 종료하게 되었습니다...!

그런 의미에서 범블비가 작성한 기획은 제가 만들었던 어플리케이션보다 가벼워서 좋네요!

저희는 '유기 동물 입양의 복잡한 절차'를 단순화하는 것과 유기 동물들의 스토리 텔링을 통해 유기 동물 입양을 도와주는 어플리케이션 이었다면 범블비는 유기 동물들을 보여주기만 하고 입양과 관련된 절차는 센터에게 맡기는 것이 장점이라는 생각이 들었습니다!

범블비의 서비스를 구현한다면 웹으로 구현하는 편이 접근성 면에서 더 유용할 것 같아요!

살펴보니 **여러** 유기 동물 보호소의 동물들을 리스팅해주는 사이트는 존재하지 않는 것 같더라구요.

이 서비스로 좋은 가치를 만들어냈으면 좋겠네요! :)

2020-06-05 08:14 UTC, slowCoyle commented on README.md
> +- 함께 행복할 반려동물을 찾고 싶음
위 페르소나만 봐서는 김시카씨가 '왜 유기 동물을 입양해야하지?' 에 대답할 수 없을 것 같아요.
펫샵에서 입양하는 것이 아닌 유기 동물을 입양해야한다는 의지가 있음을 드러내면 좋을 것같아요!

2020-06-05 13:36 UTC, fucct approved these changes
안녕하세요 범블비! 디디입니다😊
저도 동물을 좋아해서 그런지 더 관심이 가는 서비스네요! 유기동물들을 입양함으로써 사람들에게도 행복감을 주고, 유기동물 관리 기관에서도 노고를 덜 수 있어서 굉장히 좋은 아이디어라고 생각해요! 
유기동물을 무책임하게 입양하여 다시 유기를 하거나, 나쁜곳에 악용할 가능성에 대한 최소한의 안전장치를 제공해준다면 사회적으로 유익한 서비스가 될 것 같네요! 👍
제 리뷰는 지극히 저의 개인적인 의견이므로 간단히 참고만 하시면 될 것 같아요! 수고 많으셨습니다 👏

2020-06-05 13:36 UTC, fucct commented on README.md
> +
무책임하게 동물을 입양하는 문제를 막기 위한 안전 장치가 있다면 좋을 것 같아요!

2020-06-05 13:36 UTC, fucct commented on README.md
> +- 함께 행복할 반려동물을 찾고 싶음
```suggestion
- 함께 행복하게 지낼 반려동물을 찾고 싶음 
```
행복할 반려동물 이라는 표현이 살짝 어색한 것 같아요!
[여기](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=146119)를 참고하시면 좋을 것 같아요😄

2020-06-06 03:48 UTC, ksy90101 approved these changes
안녕하세요 범블비! 동물을 좋아하는 저에게는 너무 좋은 서비스로 다가왔습니다~
유기 동물에 대해서는 매년 문제가 되고 있는 이슈인데, 이런 서비스로 많이 해소되었으면 좋겠네요!
입양을 해보지는 않았지만, 유기 동물 입양도 복잡하다고 들었는데 법적으로 그런 부분들을 어떻게 하면 쉽게 사용자들이 다가갈수 있을까 고민해보시면 좋을꺼 같아요. 아울러 입양을 하면 좋은 점들을 어떻게 하면 기능적으로 사용자들에게 알릴수 있을지도 고민해보시면 좋을꺼 같습니다! 
남긴 의견은 제 생각일뿐이니 참고만 해주시면 좋을꺼 같아요!

2020-06-06 03:48 UTC, ksy90101 commented on README.md
> +- 함께 행복할 반려동물을 찾고 싶음
저도 코일과 동일합니다! 유기 동물을 입양하려는 이유가 적혀있으면 좋을꺼 같아요 ㅎㅎ

2020-06-07 08:11 UTC, ddaaac commented on README.md
> +- 함께 행복할 반려동물을 찾고 싶음
실제로 이런 서비스를 개발해보셨다니...! 대단하네요 👍  
기획할 때 입양에 관한 절차는 센터 쪽에 맡기려고 한 점을 알아주셨네요. 🙇  해당 기능은 나중에 서비스가 활성화되면 추가해보려고 생각했었습니다. 일단은 최대한 많은 사용자들이 센터를 거치게 하는게 목표라서요!
피드백 주신 입양에 대한 동기는 리뷰에 반영했습니다 :) 소중한 피드백 정말 감사합니다~

2020-06-07 08:16 UTC, ddaaac commented on README.md
> +
처음 기획했을 때 입양에 대한 책임을 서비스에서 가져갈가 센터에 넘길까 고민했었는데, 우선은 센터에 맡기기로 했습니다! 하지만 말씀해주신 장치가 있으면 훨씬 더 좋은 서비스가 될 것 같네요 :) 감사합니다 🙇

2020-06-07 08:21 UTC, ddaaac commented on README.md
> +- 함께 행복할 반려동물을 찾고 싶음
앞서 디디의 피드백과 같은 맥락의 피드백이네요. 아무래도 입양에 대한 절차나 책임까지 고려하는 것이 좋겠네요! 그리고 입양의 좋은 점들을 알릴 수 있는 방법을 찾는 것도 중요할 것 같습니다. 서비스가 지속적으로 유지되려면 꼭 필요한 고민일 것 같네요 :) 피드백 정말 감사해요 🙇

2020-06-09 02:02 UTC, pobiconan requested changes
최근 유기동물이 급격하게 늘어나는 시점에 정말 필요한 서비스라고 생각해요. 
사회적으로도 긍정적인 영향을 미칠 수 있는 서비스라 기대가 되네요. 💯 

단, git에 .idea 폴더가 추가되어 있어 이 하나만으로도 바로 merge 못하겠네요.
개발자라면 항상 ignore 처리할 파일에 신경써 주세요.

지금 페르소나와 사용자 스토리 작성한 것을 보면 입양을 하려는 사용자 입장에서만 작성했는데요.
유기 동물을 관리하는 운영자 입장, 동물을 유기하는 대신 버릴 수 밖에 없는 사람의 입장에서도 작성해 보면 어떨까요?
즉, 좀 더 다양한 사람들의 관점에서 작성해 보면 이 서비스의 색깔이 좀 더 명확해 질 것 같아요.

2020-06-09 04:38 UTC, ddaaac commented
안녕하세요 포비! 리뷰 감사합니다 :) 피드백 반영했습니다.

피드백을 반영하다보니 봉사에 관한 서비스가 추가가 됐네요. 감사합니다 👍 

제가 생각한 서비스는 센터와 강하게 협력관계를 맺어서 **수용공간과 인력이 부족한 센터의 문제**를 해결하는 것이 최우선 목표였습니다. 서비스는 단순히 연결고리 역할을 해서 많은 사람들이 센터에 관심을 갖게 하는 방식으로요. 대신, 입양에 관한 전반적인 책임은 센터가 가져가게됩니다.
말씀해주신 *동물을 유기하는 대신 버릴 수 밖에 없는 사람의 입장*까지 고려하게 된다면 서비스가 책임져야 할 사항이 늘어날 것 같습니다. 단순히 '동물을 버려야 할 수 밖에 없는 사람들과 센터를 연결해주면 되지 않냐'라고 반문할 수 있겠습니다. 하지만 제가 느끼기로는 현재 대부분의 센터들은 이미 수용 공간과 인력이 심각하게 부족합니다. 동물을 버리겠다고 하는 사람들의 수요까지 받아들이기 힘들 정도로요.
그래서 *동물을 유기하는 대신 버릴 수 밖에 없는 사람의 입장*은 서비스가 만약 성공을 거둬서 센터들이 조금 넉넉한 공간을 갖게 된다면 그 때 다시 생각해보는 게 좋을 것 같다고 생각했습니다. 그래서 1순위 페르소나는 사용자-운영자만으로 한정했습니다.

아, 그리고 ignore 파일 신경쓰겠습니다... 🙇 
다시 한번 리뷰 감사합니다!

2020-06-09 22:56 UTC, pobiconan approved these changes
이미 유기동물 보호센터의 상황까지 알고 있는 상황에서 진행하는 서비스라 더 의미있을 것 같네요. 💯 
최종 후보에 들어 빛을 볼 수 있기를...

2020-06-09 22:56 UTC, merged