[임루트] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #14
Opened 2020-06-04 08:01 UTC by p-vibe

안녕하세요~ 리뷰 부탁드립니다!
지난 번 피드백을 반영하기 위해 사용자 이야기 뿐 아니라 프로젝트의 전반적인 사항도 기술했습니다.
크루들의 많은 관심 부탁드립니다~
[여기](https://github.com/p-vibe/woowa-userstory-2020/tree/p-vibe)에서 편하게 보실 수 있습니다~

관심 가지실 크루분들을 위하여 아래 참고하실만한 사항을 따로 적습니다.
1. 본문 중 학교의 로그인 api를 활용한다고 하는 부분이 있습니다. 지인 중 학교의 api 사용을 허가받고 서비스를 만든 사람이 있는데, 학교의 로그인 api 사용을 허가받는 것은 굉장히 어려운 일이라고 합니다. 즉 로그인 api 제공 받는 것은 해결하기 어려운 이슈입니다. 따라서 당 프로젝트는 우선적으로 학교에 의존하지 않는 부분까지의 구현을 목표로 합니다.
2. 본문 중 지도 api를 사용하는 것은 가능하다고 생각하지만, 후순위 작업입니다. 기간이 길지 않기 때문에 여러 기능을 구현하려고 하기보다는 하나의 기능(채팅)을 제대로 구현하고자 합니다. 그럼에도 불구하고 팀원 중 지도 api를 사용해보고 싶은 분이 계시면 그분의 재미와 성장을 위해 지도 서비스를 도입할 수 있습니다. 다만 지도 쪽에 제가 신경을 많이 쓰지는 못할 것 같습니다.
3. 처음 기획이 "하나의 학교에 최적화된 서비스"이지만, 여기서 말하는 하나의 학교는 제 출신 학교가 아닙니다. 회의를 통해 팀원 중 한명의 학교가 될 수도 있고, 여러 학교를 통합하는 서비스가 될 수도 있습니다. 따라서 자기의 학교와 무관하게 관심 가져주시면 감사하겠습니다.

2020-06-05 10:48 UTC, toneyparky approved these changes
안녕하세요 루트~
데일리 회식이 미뤄져서 아쉽군요..! 
코로나가 얼른 잠잠해져야 할텐데 말이죠.

경험이 바탕이 된 기획서 잘 읽었습니다.
현실감 있었어요!

잘 서포트해주는 친구들이 없으면 유학생 친구들이 적응하기 힘들다는 사실을 알고 있습니다.
이 부분에 대한 해결책을 내려줄 수 있는 서비스가 되길 바라요.

지도 시스템과 접목시킨 부분은 재미있고 유학생뿐아니라 손님이라든지 새내기도 활용할 수 있을 것 같아 좋아보이네요.

에브리타임이나 유학생 커뮤니티 그리고 현실에 있는 유학생 교류 동아리와의 차별점을 조금 더 생각해보면 더 좋은 기획이 될 것 같습니다😊

수고하셨고 주말 잘 보내세요~

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +외국인 교환학생이 한국에 잘 적응할 수 있도록 도와 그들의 유학 생활 만족도를 높이고자 합니다. 나아가 더 많은 외국 학생들이 한국에 찾아오는 것에 힘을 보태서 한국의 글로벌화에 기여하고자 합니다.
멋진 목적이라 생각해요!!
저도 한국을 찾아오는 외국 친구들이 더 즐겁게 생활하면 좋겠다 생각합니다😎

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +교육통계서비스(KESS)에 따르면 외국인 유학생은 2014년까지 8만명대를 유지하다가 2015년부터 빠르게 늘어 2018년에는 14만 2천명을 기록했습니다. 필자의 개인적 경험에 따르면 입학한 2011년과 졸업한 2019년을 비교할 때 그 차이가 피부로 느껴질 정도로 유학생의 수가 늘었습니다. 유학생의 숫자가 급속도로 느는 것에 반해, 대응은 부족한 실정
공감해요 루트😢 
저도 같은 과 중국인 유학생 친구들에게 멘토링을 했었는데 개인뿐아니라 사회나 조직 내에서도 문제점이 많이 보이더라구요.

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +서비스의 사용자는 한국에 유학 온 외국인 교환학생들입니다. 아래 내용은 필자가 2017년에 약 1년간 외국인 교환학생들과 어울리며 의도치 않게 그들을 리서치한 내용에 기반합니다.
외국인 유학생 친구들에 대한 기록들 잘 봤습니다. 상세하게 적어주셔서 실제 만난 것 같네요😂

아래 페르소나로 잡으신 김철수(내국인 학생) 선생림(교수)에 대해 조사하신 부분이 있다면 더 풍부한 조사가 될 거 같아요😬

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +| 채팅 시스템 | 내국인 학생   | - 영어 공부를 하고 싶은데 원어민과 대화할 수 있는 학원은 너무 비싸다.<br />- 카카오톡 유학생 오픈 채팅을 이용해 외국인들과 만나볼까 싶지만 그들의 정체를 모르기 때문에 무섭다.<br />- 당 서비스를 이용하면 교환 학생인 게 검증이 되니 만나도 별 일 없을거라는 안심이 되고 학교 앞에서 노는 것이니 편하
이 부분은 확실히 내국인 학생 입장에서는 메리트겠네요..!

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +| 지도 시스템 | 외국인 유학생 | - 학교 어플이나 구글 맵은 보기가 힘들다. 왜냐하면 좁은 공간에서 GPS가 위치를 정확히 잡지도 못하여 지도만 보고 건물을 찾기 어렵다.<br />- 당 서비스를 이용하면 학교에 맞춘 지도 어플을 이용할 수 있어서 쉽게 건물을 찾을 수 있다. 학교에 맞췄다는 의미는 지도에서 건물을 클릭하면 이미지를 볼 수 있다는 것
학교차원에 이 기능을 지원한다는 이야기를 하며 API 권한을 획득할 수 있겠다는 생각도 듭니다!

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +| 김철수는 영어 공부를 하고 싶지만 영어 공부는 일상의 일부일 뿐 중요한 부분이 아니다. 가볍게 근처에서 외국인 친구들을 만나고 싶다. 이 때 외국인이 우리 학교 학생이라면 좀 더 믿음을 가지고 만날 수 있을 것 같다. 이에 우리 학교의 외국인 교환학생들이 많이 이용한다는 당 서비스에 접속했다. | - 사용자들을 인증해야 한다. 이 때 학교의 로그인 a
일상이 더 중요하다는 점에서 기존 유학생 교류 동아리나 프로그램과 차별화를 할 수 있겠군요!
아무래도 동아리나 프로그램에 가입한 학생은 영어 공부에 대해 더 중요하게 생각할 듯 하니말이죠!

2020-06-05 10:48 UTC, toneyparky commented on README.md
> +
정말 관계자들이 이렇게 생각하신다면 재미있겠는걸요😂

2020-06-06 03:40 UTC, p-vibe commented on README.md
> +외국인 교환학생이 한국에 잘 적응할 수 있도록 도와 그들의 유학 생활 만족도를 높이고자 합니다. 나아가 더 많은 외국 학생들이 한국에 찾아오는 것에 힘을 보태서 한국의 글로벌화에 기여하고자 합니다.
감사합니다~

2020-06-06 03:40 UTC, p-vibe commented on README.md
> +교육통계서비스(KESS)에 따르면 외국인 유학생은 2014년까지 8만명대를 유지하다가 2015년부터 빠르게 늘어 2018년에는 14만 2천명을 기록했습니다. 필자의 개인적 경험에 따르면 입학한 2011년과 졸업한 2019년을 비교할 때 그 차이가 피부로 느껴질 정도로 유학생의 수가 늘었습니다. 유학생의 숫자가 급속도로 느는 것에 반해, 대응은 부족한 실정
넵 좀 더 개선되면 좋을 것 같습니다~

2020-06-06 03:41 UTC, p-vibe commented on README.md
> +서비스의 사용자는 한국에 유학 온 외국인 교환학생들입니다. 아래 내용은 필자가 2017년에 약 1년간 외국인 교환학생들과 어울리며 의도치 않게 그들을 리서치한 내용에 기반합니다.
철수와 생림님에 대해 좀 더 추가해보겠습니다~

2020-06-06 03:42 UTC, p-vibe commented on README.md
> +| 채팅 시스템 | 내국인 학생   | - 영어 공부를 하고 싶은데 원어민과 대화할 수 있는 학원은 너무 비싸다.<br />- 카카오톡 유학생 오픈 채팅을 이용해 외국인들과 만나볼까 싶지만 그들의 정체를 모르기 때문에 무섭다.<br />- 당 서비스를 이용하면 교환 학생인 게 검증이 되니 만나도 별 일 없을거라는 안심이 되고 학교 앞에서 노는 것이니 편하
넵 내국인 학생에 대해 쓸 때 적은 것이지만, 유학생들한테도 마찬가지라고 생각합니다 유학생도 온라인의 검증되지 않은 모르는 사람을 만나는 건 무서울것같아서요~

2020-06-06 03:44 UTC, p-vibe commented on README.md
> +| 지도 시스템 | 외국인 유학생 | - 학교 어플이나 구글 맵은 보기가 힘들다. 왜냐하면 좁은 공간에서 GPS가 위치를 정확히 잡지도 못하여 지도만 보고 건물을 찾기 어렵다.<br />- 당 서비스를 이용하면 학교에 맞춘 지도 어플을 이용할 수 있어서 쉽게 건물을 찾을 수 있다. 학교에 맞췄다는 의미는 지도에서 건물을 클릭하면 이미지를 볼 수 있다는 것
그게 겁나 어렵다고 하더라고요..^^; 심지어 많은 학생들이 사용하던 서비스였는데 학교 측은 그들의 입장이 있기 때문에 쉽지 않은 것 같습니다ㅜㅜ

2020-06-06 03:56 UTC, p-vibe commented on README.md
> +
어떤 점 말씀이신가요?? 학생을 잘 구슬려 공짜로 애플리케이션을 차지하는 부분 맞나요?? 실제로 지인 개발자가 많은 학생들이 쓰는 어플리케이션을 만들어 하루 평균 1,000명이 사용하는 서비스를 5년간 운영했는데 학교가 거저 먹으려고 한 걸 기반으로 작성해봤습니다~! 물질적 보상 없이 5년간 서비스 운영에 대한 공로 인정만 요청했는데도 불구하고 학교는 앱을 자기들이 운영해겠다는 말만 했다고 하네요!

2020-06-06 06:43 UTC, sonypark reviewed
루트 서비스 기획서 잘 봤습니다!
무엇보다 경험에 기반한 풍부한 잠재 사용자 분석과 시나리오 작성이 인상적이었습니다.
교내 활동에서 제공하지 못하는 부분을 특정 학교와 위치에 기반한 채팅 서비스를 통해 보완하려고 하는게 재미있네요.
에브리타임의 경우 외국인 학생이 사용하기는 어렵기도 해서, 외국인 교환 학생을 타겟팅하는 서비스에 집중하면 차별화가 생길 것 같아요.

궁금한 점은 코멘트로 남겼으니 확인 부탁드릴게요~

2020-06-06 06:43 UTC, sonypark commented on README.md
> +| 채팅 시스템 | 내국인 학생   | - 영어 공부를 하고 싶은데 원어민과 대화할 수 있는 학원은 너무 비싸다.<br />- 카카오톡 유학생 오픈 채팅을 이용해 외국인들과 만나볼까 싶지만 그들의 정체를 모르기 때문에 무섭다.<br />- 당 서비스를 이용하면 교환 학생인 게 검증이 되니 만나도 별 일 없을거라는 안심이 되고 학교 앞에서 노는 것이니 편하
GPS 기반으로 학교 근처 사람만 채팅이 가능하게 하는건가요?
학교 근처의 기준이 어디까지인지 궁금하네요.(ex. 학교 반경 몇 미터 이내)
학교 근처가 아닌 학생은 채팅을 할 수 없는데, 학교에서 좀 먼거리에서 자취하고 있는 학생은 채팅을 못 하지 않을까요?

2020-06-06 06:43 UTC, sonypark commented on README.md
> +
이 서비스의 목적이 외국인 학생들과 한국인 학생들이 채팅방을 통해 자유롭게 놀 수 있는 공간을 마련해주는 것이라고 생각하는데요.
학교 관계자들을 위한 관리 기능이 꼭 필요한건가요~~? 학교 api를 제공받기 힘들고 자체 서비스로 제작하는거라면 이 기능은 필요하진 않을 것 같아서요!

2020-06-06 06:43 UTC, sonypark commented on README.md
> +
교환학생 대부분이 공부보다는 즐겁게 놀다가려는 친구들이 많죠!ㅎㅎㅎ 이러한 특징에 기반하여 '그들이 더 잘 놀 수 있게 도와주는 기능에 집중'하려는게 좋은 것 같아요! 👍

2020-06-06 06:56 UTC, p-vibe commented on README.md
> +| 채팅 시스템 | 내국인 학생   | - 영어 공부를 하고 싶은데 원어민과 대화할 수 있는 학원은 너무 비싸다.<br />- 카카오톡 유학생 오픈 채팅을 이용해 외국인들과 만나볼까 싶지만 그들의 정체를 모르기 때문에 무섭다.<br />- 당 서비스를 이용하면 교환 학생인 게 검증이 되니 만나도 별 일 없을거라는 안심이 되고 학교 앞에서 노는 것이니 편하
넵 저는 가능할 것 같습니다! 모바일에서 gps 정보를 받아서 서버에 쏴주면, 서버에서 접근 가능한 위치인지 검증하면 됩니다! 어느 정도의 거리까지 채팅이 가능하게 할지는 기획 정책에 따라 원하는대로 변화를 줄 수 있을 것 같습니다

2020-06-06 06:58 UTC, p-vibe commented on README.md
> +
넵 저도 동의합니다! 소니 말씀대로 학교와 딱히 협업할 필요가 없다면 관리 기능은 필요 없을 것 같습니다..^^; 기획 단계에서는 학교와의 협업을 염두해두었기 때문에 학교 측에 줄 수 있는 가치를 생각해봤습니다!

2020-06-06 06:59 UTC, p-vibe commented on README.md
> +
감사합니다~

2020-06-06 10:12 UTC, KimGyeong approved these changes
안녕하세요 임루트! 신선한 아이디어여서 재미있게 읽었습니다 😁

여러 나라의 교환 학생들을 타겟팅한다면 여러 언어를 지원해야 하는 문제점도 있겠네요!

다음 보고서에 추가될 것들이 있을 것 같네요. 잘 정리해봅시다!

2020-06-06 10:12 UTC, KimGyeong commented on README.md
> +리서치를 통해 교환학생들의 주된 Needs가 노는 것이라는 걸 알 수 있었습니다. 이에 그들이 더 잘 놀 수 있게 도와주는 기능에 집중하고자 합니다. 주관적으로 외국인 유학생들이 대체로 외향적이라고 느껴, 그들의 주도 하에 쉽게 다양한 만남을 가질 수 있게하면 그들의 즐거운 유학 생활을 도울 수 있다고 판단하였습니다. 또한 리서치를 통해 유학생들은 노는
교환학생이 영어권 학생이 아니어서 한국학생이 피한다면,

배경에서 나온 것과 같이 유학생 - 한국 학생 매칭 시스템의 문제점과 동일한 문제가 발생하지 않을까요?

아이디어의 배경과 잠재적 사용자들의 니즈가 일치하지 않는 느낌이네요.

2020-06-06 10:12 UTC, KimGyeong commented on README.md
> +| 지도 시스템 | 외국인 유학생 | - 학교 어플이나 구글 맵은 보기가 힘들다. 왜냐하면 좁은 공간에서 GPS가 위치를 정확히 잡지도 못하여 지도만 보고 건물을 찾기 어렵다.<br />- 당 서비스를 이용하면 학교에 맞춘 지도 어플을 이용할 수 있어서 쉽게 건물을 찾을 수 있다. 학교에 맞췄다는 의미는 지도에서 건물을 클릭하면 이미지를 볼 수 있다는 것
건물 내부가 아닌 건물 자체를 찾는 것이라면 거리 뷰를 이용하는 것과 비교하여 어떤 장점이 있을까요?

2020-06-06 11:07 UTC, p-vibe commented on README.md
> +| 지도 시스템 | 외국인 유학생 | - 학교 어플이나 구글 맵은 보기가 힘들다. 왜냐하면 좁은 공간에서 GPS가 위치를 정확히 잡지도 못하여 지도만 보고 건물을 찾기 어렵다.<br />- 당 서비스를 이용하면 학교에 맞춘 지도 어플을 이용할 수 있어서 쉽게 건물을 찾을 수 있다. 학교에 맞췄다는 의미는 지도에서 건물을 클릭하면 이미지를 볼 수 있다는 것
주관적으로 거리뷰보다 편하지 않을까 생각합니다!! ㅎㅎ

2020-06-06 11:09 UTC, p-vibe commented on README.md
> +리서치를 통해 교환학생들의 주된 Needs가 노는 것이라는 걸 알 수 있었습니다. 이에 그들이 더 잘 놀 수 있게 도와주는 기능에 집중하고자 합니다. 주관적으로 외국인 유학생들이 대체로 외향적이라고 느껴, 그들의 주도 하에 쉽게 다양한 만남을 가질 수 있게하면 그들의 즐거운 유학 생활을 도울 수 있다고 판단하였습니다. 또한 리서치를 통해 유학생들은 노는
배경은 유학생들이 어려움을 겪고 있다는 점에 공감대를 얻고자 했습니다! 배경에서 적어놓은 것은 예시일 뿐입니다!^^

2020-06-06 12:02 UTC, lalize approved these changes
안녕하세요~ 임루트√ ~

특정 위치에서만 접속 가능한 서비스! 참신하네요 🤩
교환학생과 내국인 학생이 서로 신뢰를 기반으로 빠르게 만나서 놀 수 있도록 도와주는 점 👍

2020-06-06 12:02 UTC, lalize commented on README.md
> +한국에 유학 온 외국인 교환학생들을 대상으로 한 채팅 서비스입니다. 기존 채팅 서비스와의 차이점은 특정 학교의 재학생만 특정 위치에서 서비스에 접근할 수 있다는 것입니다.
특정 위치에서만 접속할 수 있는 서비스는 처음 보는 것 같아요!

2020-06-06 12:02 UTC, lalize commented on README.md
> +리서치를 통해 교환학생들의 주된 Needs가 노는 것이라는 걸 알 수 있었습니다. 이에 그들이 더 잘 놀 수 있게 도와주는 기능에 집중하고자 합니다. 주관적으로 외국인 유학생들이 대체로 외향적이라고 느껴, 그들의 주도 하에 쉽게 다양한 만남을 가질 수 있게하면 그들의 즐거운 유학 생활을 도울 수 있다고 판단하였습니다. 또한 리서치를 통해 유학생들은 노는
특정 지역이 아닌 곳에서는 이전에 채팅한 유학생 친구와도 채팅을 못하는 건가요? 🤔

2020-06-06 12:02 UTC, lalize commented on README.md
> +| Peter는 교양 수업을 듣기 위해 경영관에 가야 하는데, 지도를 보고서는 경영관을 찾기가 힘들다. 지도에 표시된 건물이 어떻게 생겼는지 보고, 내 앞에 있는 저 건물이 경영관인지 아닌지 확인하고 싶다. 이에 우리 학교 맞춤 지도 서비스를 제공한다는 당 서비스에 접속했다. | - 지도 내 건물을 클릭하면 이미지를 보여줄 수 있어야 한다.    |
데이터를 수집해서 지도를 일일이 만드는 건가요?!
교환 학생과 매칭해주는 채팅 서비스에 필요한 기능인지 생각해볼 필요가 있을 것 같아요.

2020-06-06 12:02 UTC, lalize commented on README.md
> +| 김철수는 영어 공부를 하고 싶지만 영어 공부는 일상의 일부일 뿐 중요한 부분이 아니다. 가볍게 근처에서 외국인 친구들을 만나고 싶다. 이 때 외국인이 우리 학교 학생이라면 좀 더 믿음을 가지고 만날 수 있을 것 같다. 이에 우리 학교의 외국인 교환학생들이 많이 이용한다는 당 서비스에 접속했다. | - 사용자들을 인증해야 한다. 이 때 학교의 로그인 a
모든 학교가 로그인 API를 지원하고 있나요? 🤔

2020-06-06 12:02 UTC, lalize commented on README.md
> +| 선생림은 점점 늘어나는 국제 학생들을 잘 관리하고 싶다. 국제 학생들을 위한 예산도 책정되어 있는 상태다. 마침 교내 학생이 국제 학생들을 위한 애플리케이션을 만들테니 로그인 api를 제공해달라고 한다. 교내 학생이 어플리케이션을 만들면 대외적으로 홍보할 수도 있고, 학생을 잘 구슬려 공짜로 애플리케이션을 차지할 수 있을 것 같아 로그인 api를 제공
학교 측에서 third-party 앱을 위한 인증 시스템을 구현해야겠네요... 쉽진 않을 것 같아요.
그렇다면 학교 메일 인증은 어떨까요?

2020-06-06 12:42 UTC, p-vibe commented on README.md
> +| 김철수는 영어 공부를 하고 싶지만 영어 공부는 일상의 일부일 뿐 중요한 부분이 아니다. 가볍게 근처에서 외국인 친구들을 만나고 싶다. 이 때 외국인이 우리 학교 학생이라면 좀 더 믿음을 가지고 만날 수 있을 것 같다. 이에 우리 학교의 외국인 교환학생들이 많이 이용한다는 당 서비스에 접속했다. | - 사용자들을 인증해야 한다. 이 때 학교의 로그인 a
아니오 모릅니다! ㅎㅎ

2020-06-06 12:43 UTC, p-vibe commented on README.md
> +| Peter는 교양 수업을 듣기 위해 경영관에 가야 하는데, 지도를 보고서는 경영관을 찾기가 힘들다. 지도에 표시된 건물이 어떻게 생겼는지 보고, 내 앞에 있는 저 건물이 경영관인지 아닌지 확인하고 싶다. 이에 우리 학교 맞춤 지도 서비스를 제공한다는 당 서비스에 접속했다. | - 지도 내 건물을 클릭하면 이미지를 보여줄 수 있어야 한다.    |
넵 예전에 제 혼자 만들려고 할 때는 학교의 건물들을 일일이 찍었었습니다.
넵 생각해보겠습니다!

2020-06-06 12:44 UTC, p-vibe commented on README.md
> +리서치를 통해 교환학생들의 주된 Needs가 노는 것이라는 걸 알 수 있었습니다. 이에 그들이 더 잘 놀 수 있게 도와주는 기능에 집중하고자 합니다. 주관적으로 외국인 유학생들이 대체로 외향적이라고 느껴, 그들의 주도 하에 쉽게 다양한 만남을 가질 수 있게하면 그들의 즐거운 유학 생활을 도울 수 있다고 판단하였습니다. 또한 리서치를 통해 유학생들은 노는
지역 채팅방에선 못합니다!
일대일 방에선 가능합니다~

2020-06-06 12:45 UTC, p-vibe commented on README.md
> +한국에 유학 온 외국인 교환학생들을 대상으로 한 채팅 서비스입니다. 기존 채팅 서비스와의 차이점은 특정 학교의 재학생만 특정 위치에서 서비스에 접근할 수 있다는 것입니다.
그런가요??
이 아이디어 꺼낼 때 가장 먼저 받는 피드백이 위치 기반 채팅 너무 많이 들어봤다고 그러더라고요...ㅎㅎ
저도 못봐서 만들려고 했는데 있긴 한가봐요
아직 유명한 건 없는 것 같습니다!

2020-06-06 12:47 UTC, p-vibe commented on README.md
> +| 선생림은 점점 늘어나는 국제 학생들을 잘 관리하고 싶다. 국제 학생들을 위한 예산도 책정되어 있는 상태다. 마침 교내 학생이 국제 학생들을 위한 애플리케이션을 만들테니 로그인 api를 제공해달라고 한다. 교내 학생이 어플리케이션을 만들면 대외적으로 홍보할 수도 있고, 학생을 잘 구슬려 공짜로 애플리케이션을 차지할 수 있을 것 같아 로그인 api를 제공
만약 학교가 추가적인 인증 시스템을 구현해야 하는 상황이라면,
학교의 인증을 포기하거나 그 학교를 포기하거나 하겠습니다!ㅎㅎ
오 메일 인증도 괜찮은 것 같네요!
좋은 아이디어 감사합니다 ㅎㅎ

2020-06-07 03:25 UTC, sonypark approved these changes

2020-06-08 03:53 UTC, toneyparky commented on README.md
> +
제가 표현을 모호하게 사용했네요.
의도치 않게 기분 상하게 해드렸다면 사과드립니다.
실제로 저런 상황이었다면 몹시 기분이 나빴겠네요.

저는 말도 안되는 생각이라고 여겨서 재미있다라고 표현했었습니다만 현실에서 벌어진 일이라니 슬플따름입니다..

2020-06-09 03:05 UTC, woowahanCU requested changes
전에 고민했던 주제를 다시 반추하며 기획서를 작성해서인지, 덕분에 재밌게 잘 읽었습니다. 👍 
몇가지 Comment 남겨두었는데요. 확인해보시고 궁금한 점 있으면 메시지 남겨주세요~ 
좋은 하루 보내요! 😀

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +리서치를 통해 교환학생들의 주된 Needs가 노는 것이라는 걸 알 수 있었습니다. 이에 그들이 더 잘 놀 수 있게 도와주는 기능에 집중하고자 합니다. 주관적으로 외국인 유학생들이 대체로 외향적이라고 느껴, 그들의 주도 하에 쉽게 다양한 만남을 가질 수 있게하면 그들의 즐거운 유학 생활을 도울 수 있다고 판단하였습니다. 또한 리서치를 통해 유학생들은 노는
**작업을 이해하는 것도 중요하지만, 왜 그 작업이 존재하는지 이해해야 하는 것** 이 중요한데요.
주된 Needs가 노는 것이라면,
놀기 위해서 우선 교환학생들이 어떤 작업을 하는걸까요?
그리고 각자 놀기 위해 어떤 행동들을 취하는지, 그리고 모임을 갖는다면 어떤 단계, 방법으로 접근하는지가 좀 더 분명히 드러나면 좋을거 같아요. 

주된 니즈가 노는 것이라는 점, 노는 곳이 뻔하다는 점, 이에 특정 지역에서만 접근 가능한 채팅 서비스가 필요할 거라는 점간에 논리가 다소 빈약한거 같아요.

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +4. Customer Job
Customer Job은 실제 Persona의 직업을 의미하는 것이 아니라,
Persona가 이 서비스를 통해 궁극적으로 달성하는 목표를 의미합니다.
서비스에서의 고객의 주 역할이라고 이해하심 좋겠네요.

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +   교환학생
Peter가 1순위 Persona일까요?
Persona는 앞으로 서비스를 만들어가는 과정에서, 서로 다른 직군/팀의 사람들이 공통된 컨셉을 지향하기 위해 구상하는 것이라 보시면 되요. 
새로운 사람과 노는 걸 좋아한다고 하더라도, 오프라인에서 술을 먹는 걸 좋아하는지, 여행 가는걸 좋아하는지, 독서모임을 좋아하는지 혹은 온라인에서 어떤 형태로 만남을 가지는 것을 좋아하는지 등에 따라 서비스 디자인 컨셉부터 여러 기능들이 달라질 거거든요.
그래서 Persona는 머릿속으로 그려질 정도로 풍부히 묘사해주는 것이 좋습니다.
그렇게 특정 대상을 위한 특정 기능들을 만들어가다 새로운 타겟 유저가 등장하면 그에 맞춰 추가적인 논의들이 이루어지면 됩니다.

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +   교환학생
추가적으로, Persona를 작성함에 앞서서 패턴을 분석하는 것이 상당히 중요합니다.
각 인터뷰 참가자들 간에 어떤 행동의 차이가 있는지를 보고 군집한 부분이 있다면 이를 통해 공통된 사용자로 도출하는 것이지요.

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +| Peter는 따분한 한국 수업을 듣고나서 내가 이러려고 한국에 왔나 하는 자괴감이 든다. 여러 사람들과 재밌게 놀고 싶은 그는 자기와 같은 교환학생을 위해 만들었다는 당 서비스에 사람들과 이야기하기 위해 접속했다. | - 채팅이 가능해야 한다.                                      |
자괴감이 든다와 같은 부분은, 실제 시스템과의 인터랙션을 통해 해소할 목표가 아니라면 굳이 언급하지 않으셔도 됩니다.
오히려 불필요한 묘사는 서비스를 기획하는데 방해를 줄 수 있습니다. 
우리가 집중해야 할 부분이 무엇인지 드러내는 것이 중요합니다.

---

이야기는 게시판을 통해서도 이야기할 수 있고, 음성 채팅도 가능할 텐데요. 여기서는 어떤 의미일까요?

---

- 교환학생을 위해 만들었다면, 교환학생인지를 확인하는 요구사항이 필요하지 않을까요
- 재밌게 놀기 위해서는 채팅만 제공해주면 되나요? 아니면, 채팅 이후에 다음 단계로 유도하는 부분이 있는걸까요?

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +| 시나리오                                                     | 요구사항                                                     |
위의 시나리오와는 다른 내용이네요? 🤔

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +| Peter는 타 채팅 서비스를 이용해 친구를 만나려고 했지만 다들 멀리 있어서 만나기가 어렵다. 학교 근처의 사람들만 접속할 수 있다는 당 서비스에 사람들과 이야기 하기 위해 접속했다. | - 위치에 따라 접근할 수 있어야 한다.                         |
Peter는 늘 학교 근처에 있는 성실한 사람이군요!
Peter는 놀기 위해서는 우선 학교 근처로 가는걸까요?

---

학교 근처에는 사람들이 굉장히 많을텐데요. 위치 기반으로만 우선 접속하면 되는 걸까요?
채팅방을 나눈다면 Peter는 어떤 채팅방은 개설하거나 접속할까요?
그게 아니라면, Peter는 어떤 형태로 대화에 참여할까요?

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +| Peter는 교양 수업을 듣기 위해 경영관에 가야 하는데, 지도를 보고서는 경영관을 찾기가 힘들다. 지도에 표시된 건물이 어떻게 생겼는지 보고, 내 앞에 있는 저 건물이 경영관인지 아닌지 확인하고 싶다. 이에 우리 학교 맞춤 지도 서비스를 제공한다는 당 서비스에 접속했다. | - 지도 내 건물을 클릭하면 이미지를 보여줄 수 있어야 한다.    |
놀고 싶어하는 Peter가 이 서비스를 이용해서 학교를 탐방하나요?
지도는 네이버나 카카오도 있는데요. 이 서비스를 통해서 학교를 탐방할 때의 이점은 무엇일까요
채팅방에서 수업이 열리는 정확한 위치(경영관 4층 복도끝 등)나 수업이 지금 진행중인지 등 네이버니 카카오를 통해 알기 힘든 정보를 묻는 시나리오는 어떨까요

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +| 김철수는 영어 공부를 하고 싶지만 영어 공부는 일상의 일부일 뿐 중요한 부분이 아니다. 가볍게 근처에서 외국인 친구들을 만나고 싶다. 이 때 외국인이 우리 학교 학생이라면 좀 더 믿음을 가지고 만날 수 있을 것 같다. 이에 우리 학교의 외국인 교환학생들이 많이 이용한다는 당 서비스에 접속했다. | - 사용자들을 인증해야 한다. 이 때 학교의 로그인 a
우선은 1순위 Persona에 집중하는 것이 좋을거 같네요.
다른 타겟 유저를 위한 기능/UI/UX 등은 버전 2에서 고민해보는 것은 어떨까요

2020-06-09 03:05 UTC, woowahanCU commented on README.md
> +| 선생림은 점점 늘어나는 국제 학생들을 잘 관리하고 싶다. 국제 학생들을 위한 예산도 책정되어 있는 상태다. 마침 교내 학생이 국제 학생들을 위한 애플리케이션을 만들테니 로그인 api를 제공해달라고 한다. 교내 학생이 어플리케이션을 만들면 대외적으로 홍보할 수도 있고, 학생을 잘 구슬려 공짜로 애플리케이션을 차지할 수 있을 것 같아 로그인 api를 제공
교환학생들의 데이터가 쌓이고 사용이 원활하다면 역으로 각 학교 측에서 요구할수도 있을거에요.
현재 학교 가정통신문을 대체하고 있는 아이엠스쿨이 어떻게 확장해갔는지를 확인해보는 것도 좋을거 같네요
하지만, 이 또한 1순위 Persona와는 거리가 먼 부분이니 훗날 다시 논의할 때는 지금과는 다른 형태로 이야기가 진행될거라 생각해요

2020-06-09 04:24 UTC, p-vibe commented on README.md
> +| Peter는 타 채팅 서비스를 이용해 친구를 만나려고 했지만 다들 멀리 있어서 만나기가 어렵다. 학교 근처의 사람들만 접속할 수 있다는 당 서비스에 사람들과 이야기 하기 위해 접속했다. | - 위치에 따라 접근할 수 있어야 한다.                         |
아하 이 부분은 제가 다른 학교도 제가 다니던 학교와 비슷할거라고 생각해서 설명을 부족하게 적은 것 같습니다!
Peter가 학교 근처에 있을 거라고 생각한 것은, 제 모교에서는 교환학생들이 대부분 학교의 기숙사에서 살거나, 학교 근처 고시원에 살던 것에 기반하여 추측한 것이었습니다!
Peter의 페르소나에 명시하도록 하겠습니다 ㅎㅎ
----------------------------------------------------------------------------------------
위치 기반으로만 접속하는 걸 생각했었습니다!
Peter는 새로운 채팅방을 만들 순 없고, 이미 만들어진 채팅방에 접속만 할 수 있는걸 생각했는데요
예를 들어 왕십리방(왕십리 6번출구 앞 술집이 모여진 곳), 이태원방, 기숙사방이 이미 만들어져있고 피터가 그 위치에 없다면 그 방에 몇명이 있는지만 확인할 수 있습니다.
그리고 미리 정해놓은 구역에 위치하면 그 방에 입장하여 대화에 참여하는 것을 구상하였습니다

카카오톡처럼 채팅방을 만드는 시나리오도 생각하고 있지만, 후순위 작업으로 생각하고 있습니다!

뭔가 써보니 많이 빈약한 느낌이 드네요 ㅜㅜ ux적으로 불편할 것 같기도 하고...ㅠㅠ

2020-06-09 04:36 UTC, p-vibe commented on README.md
> +| Peter는 교양 수업을 듣기 위해 경영관에 가야 하는데, 지도를 보고서는 경영관을 찾기가 힘들다. 지도에 표시된 건물이 어떻게 생겼는지 보고, 내 앞에 있는 저 건물이 경영관인지 아닌지 확인하고 싶다. 이에 우리 학교 맞춤 지도 서비스를 제공한다는 당 서비스에 접속했다. | - 지도 내 건물을 클릭하면 이미지를 보여줄 수 있어야 한다.    |
그것도 좋을 것 같습니다~ 확실히 기존 지도 서비스보다 차별화되는 점이 부족한 것 같습니다 ㅜㅜ

지도 서비스를 계획했던 것은 네이버나 카카오, 학교 어플 지도를 보기 어렵다는 의견에 기반한 것이었는데요!
개인적으로 기존의 어플들이 사용이 어려운 이유를 한번 추측해봤는데요, 학교는 좁은 거리도 있고 건물도 뭉쳐 있기 때문에 gps가 10~20m정도 틀릴 때 일반적인 길찾기보다 헷갈릴 거라도 생각했습니다
그래서 지도 api에 각 건물의 이미지를 추가하면 gps가 알려주는 내 위치에 의존하지 않고 건물들을 클릭해보며 내 위치를 추측하며 건물을 찾고, 원하던 건물 앞에 도착했을 때도 이미지를 보고 확실히 '내가 원하던 곳이구나'를 알 수 있을 것이라고 생각했었습니다

하지만 크루들이 거리뷰와의 차별점이 부족한 것 같다고 피드백을 주었고, 저도 공감이 됐습니다.
지도 서비스를 적용하려면 씨유 말씀대로 확실히 차별점을 두거나, 아니면 아예 지도 서비스를 빼는 것이 나을수도 있을 것 같습니다

한번 씨유가 조언해주신대로 차별화를 두는 쪽으로 수정해보겠습니다!

2020-06-09 04:36 UTC, p-vibe commented on README.md
> +| 김철수는 영어 공부를 하고 싶지만 영어 공부는 일상의 일부일 뿐 중요한 부분이 아니다. 가볍게 근처에서 외국인 친구들을 만나고 싶다. 이 때 외국인이 우리 학교 학생이라면 좀 더 믿음을 가지고 만날 수 있을 것 같다. 이에 우리 학교의 외국인 교환학생들이 많이 이용한다는 당 서비스에 접속했다. | - 사용자들을 인증해야 한다. 이 때 학교의 로그인 a
네 그렇게 수정하도록 하겠습니다 감사합니다!

2020-06-09 04:37 UTC, p-vibe commented on README.md
> +| 선생림은 점점 늘어나는 국제 학생들을 잘 관리하고 싶다. 국제 학생들을 위한 예산도 책정되어 있는 상태다. 마침 교내 학생이 국제 학생들을 위한 애플리케이션을 만들테니 로그인 api를 제공해달라고 한다. 교내 학생이 어플리케이션을 만들면 대외적으로 홍보할 수도 있고, 학생을 잘 구슬려 공짜로 애플리케이션을 차지할 수 있을 것 같아 로그인 api를 제공
그렇군요
넵 가능성은 열어두되, 1순위 페르소나는 아니니 1순위 페르소나에 집중하는 방향으로 수정해보겠습니다!

2020-06-09 04:43 UTC, p-vibe commented on README.md
> +| Peter는 따분한 한국 수업을 듣고나서 내가 이러려고 한국에 왔나 하는 자괴감이 든다. 여러 사람들과 재밌게 놀고 싶은 그는 자기와 같은 교환학생을 위해 만들었다는 당 서비스에 사람들과 이야기하기 위해 접속했다. | - 채팅이 가능해야 한다.                                      |
피식하는 웃음을 의도했던 것이 화를 불렀군요...!^^;; 집중할 부분을 드러내는 방향으로 수정하도록 하겠습니다

여기서 이야기는 글자 채팅을 뜻한 것이었습니다! 애매한 표현을 제거하고 구체적으로 수정하도록 하겠습니다

1. 네 맞습니다 그 부분이 사실 가장 큰 이슈사항이라고 생각하고 있습니다ㅜㅜ 학교 api를 활용하면 가장 좋겠지만, 초기 단계에서는 어려운 부분일 수 있다고 생각하고, 차안으로 크루들이 제안해준 이메일 인증 방식을 고려하고 있습니다. 학교 계정만 허용하는 방안으로 하면 이메일 인증이 학교 로그인 api를 활용하는 것의 대안이 될 수 있을 것 같습니다!
2. 현재는 채팅만 생각하고 있습니다! 사용자들이 모이고, 그들의 요구사항을 더욱 구체적으로 알게되면 그 때 그들의 니즈에 대응할 계획을 가지고 있습니다!

2020-06-09 04:44 UTC, p-vibe commented on README.md
> +| 시나리오                                                     | 요구사항                                                     |
그렇네요! 시나리오와 매칭이 되도록 수정하겠습니다!

2020-06-09 04:45 UTC, p-vibe commented on README.md
> +4. Customer Job
그렇군요 알겠습니다 이해를 바탕으로 수정해보도록 하겠습니다!

2020-06-09 04:47 UTC, p-vibe commented on README.md
> +리서치를 통해 교환학생들의 주된 Needs가 노는 것이라는 걸 알 수 있었습니다. 이에 그들이 더 잘 놀 수 있게 도와주는 기능에 집중하고자 합니다. 주관적으로 외국인 유학생들이 대체로 외향적이라고 느껴, 그들의 주도 하에 쉽게 다양한 만남을 가질 수 있게하면 그들의 즐거운 유학 생활을 도울 수 있다고 판단하였습니다. 또한 리서치를 통해 유학생들은 노는
그렇군요..ㅜㅜ
이야기 나눌 수 있는 공간을 제공해주면 그들끼리 더 잘 놀것이라고 생각했는데 씨유의 피드백을 받고보니 굉장히 나이브한 생각이었던 것 같습니다

좀더 구체적으로 적어보도록 하겠습니다!

2020-06-10 04:23 UTC, woowahanCU commented on README.md
> +| Peter는 타 채팅 서비스를 이용해 친구를 만나려고 했지만 다들 멀리 있어서 만나기가 어렵다. 학교 근처의 사람들만 접속할 수 있다는 당 서비스에 사람들과 이야기 하기 위해 접속했다. | - 위치에 따라 접근할 수 있어야 한다.                         |
그래서 사용자 리서치를 하고 공통된 부분을 도출해서 타겟 유저를 선정하는거에요
모든 사용자를 위한 서비스를 한번에 만들어내는 것은 어렵거든요.
가장 핵심이 되는 부분이 무엇일지 계속 고민해보는 것은 좋은 서비스를 만드는데 중요한 자세인거 같아요 ㅎㅎ

2020-06-10 04:25 UTC, woowahanCU commented on README.md
> +| Peter는 교양 수업을 듣기 위해 경영관에 가야 하는데, 지도를 보고서는 경영관을 찾기가 힘들다. 지도에 표시된 건물이 어떻게 생겼는지 보고, 내 앞에 있는 저 건물이 경영관인지 아닌지 확인하고 싶다. 이에 우리 학교 맞춤 지도 서비스를 제공한다는 당 서비스에 접속했다. | - 지도 내 건물을 클릭하면 이미지를 보여줄 수 있어야 한다.    |
이것은 제 의견이라, 서비스에 반영하는 것은 위험할 수 있어요.
임루트가 알고 있는 실제 사용자들이 어떤 형태로 학교 건물들을 탐방하는지를 먼저 관찰해보는게 좋을거 같아요.
기존 지도가 어렵다면 어느 부분에서 시간을 소요하고 있고 그래서 어떻게 찾고 있는지를요.

2020-06-10 17:19 UTC, ttkmw commented on README.md
> +| Peter는 교양 수업을 듣기 위해 경영관에 가야 하는데, 지도를 보고서는 경영관을 찾기가 힘들다. 지도에 표시된 건물이 어떻게 생겼는지 보고, 내 앞에 있는 저 건물이 경영관인지 아닌지 확인하고 싶다. 이에 우리 학교 맞춤 지도 서비스를 제공한다는 당 서비스에 접속했다. | - 지도 내 건물을 클릭하면 이미지를 보여줄 수 있어야 한다.    |
넵 그런데 패턴분석을 해봤더니 지도 서비스에 대한 니즈가 별로 없는 것 같아 뺐습니다!

2020-06-10 17:19 UTC, ttkmw commented on README.md
> +| Peter는 타 채팅 서비스를 이용해 친구를 만나려고 했지만 다들 멀리 있어서 만나기가 어렵다. 학교 근처의 사람들만 접속할 수 있다는 당 서비스에 사람들과 이야기 하기 위해 접속했다. | - 위치에 따라 접근할 수 있어야 한다.                         |
넵!!

2020-06-10 17:20 UTC, ttkmw commented on README.md
> +   교환학생
넵 패턴 분석을 통해 1순위 페르소나를 구체화해봤습니다!

2020-06-10 17:27 UTC, ttkmw commented
@woowahanCU 
패턴 분석에 특히 집중하며 수정해봤는데, 씨유의 의도를 잘 반영한 것인진 모르겠습니다..!^^;;
리뷰 부탁드립니다~ ㅎㅎ

2020-06-11 00:30 UTC, woowahanCU approved these changes
피드백 반영하느라 고생많으셨어요! 👍 
최종 기획서도 잘 준비하셔서 프로젝트로 볼 수 있길 바래요~ 
오늘 하루 잘 보내요! 😀

2020-06-11 00:30 UTC, woowahanCU commented on README.md
> +   채팅 서비스 이용
Customer Job은 이 서비스에서의 고객의 역할을 의미해요.
즉, Peter가 궁극적으로 달성하고자 하는 목표가 되겠지요

2020-06-11 00:30 UTC, merged