[학성] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #2
Opened 2020-06-04 01:26 UTC by ordinCode

[여기]서 확인할 수 있습니다.

[여기]: https://github.com/ordinCode/woowa-userstory-2020/tree/ordincode

2020-06-04 10:15 UTC, ParkDooWon reviewed
안녕하세요 학성! 만나서 반가워요~~
학성이 작성한 시나리오 잘 읽어봤습니다. :)
우선 반응이 없는 청중들의 생각과 반응을 얻기 위해서 서비스를 만드는 아이디어가 좋은 것 같아요. 어떻게든 청중들의 생각을 알고나면 강의를 진행할 방향을 더 쉽게 잡을 수 있을 것 같아요. 그리고 자주 할 질문에 대해서 기억에 의존하지 않고 데이터로 남기는 것이 특히 좋았던 것 같아요. :)

그런데 저는 그러면 강의를 듣는 학생들은 `강사가 답변을 얻기 위해 강의마다 이 어플을 깔아야하는 것인가?` 하는 궁금증이 생겼어요. 강사에게는 분명히 큰 도움이 될 어플인데 학생들의 입장에서는 설치를 할 이유가 적어보였어요. 그래서 `어떻게 응답자들이 답변을 하게 만들 것인지`에 대해서 고민해보면 좋을 것 같습니다! :)

2020-06-04 10:15 UTC, ParkDooWon commented on README.md
> +또한 거의 모든 강의마다 하던 질문이 있었는데 사람들의 답변들을 기억에만 의존하지않고 구제적인 데이터로 가지고 있다면, 트렌드 파악도 되고 그것에 기초하여 강연을 보완하거나 혹은 사람들의 니즈를 충족시키는 주제로 강의를 기획할 수 있을 것 같다.
자주 하는 질문을 날리지 않고, 데이터를 모아서 발전에 활용한다는 부분이 좋네요 :)

2020-06-04 10:15 UTC, ParkDooWon commented on README.md
> +## 요구사항 도출
저는 시나리오와 요구사항에 `학생을 위한 보상` 같은 것이 있으면 좋을 것 같아요. :)

`가장 많은 답변을 한 학생에게 커피 쿠폰이 지급된다` 같이 학생이 이 서비스에 참여할 이유를 넣는 것은 어떨까요?
성실히 답한 학생에게 보상을 주는 것까지를 서비스의 일부로 둬도 되지않을까요?? (잘 몰라서 정말 의견이 궁금합니다.😃)

2020-06-05 09:33 UTC, kouz95 approved these changes
안녕하세요 학성! 글쓰기 피드백 드리던 때가 생각나네요. 유독 이런 자리에서 많이 만나게 되는 것 같아요! 😁

꼭 강사뿐만 아니라, 많은 사람들의 의견을 수집할때 사용하기 좋은 아이디어라고 생각이 드네요!
단순히 휘발성이 아니라 답변들을 저장해준다는 것도 좋아요! 🌟

때문에, 제가 생각할때 이 서비스가 집중해야 할 부분은 UI/UX 인것 같아요!
사람들의 의견이 궁금할때 질문을 열고, 질문에 대한 답변을 받고, 이후에 답변들을 조회하는 각각의 과정들이 손쉽게 이루어 진다면 안 쓸 이유가 없는 서비스가 될 것 같아요!

기대하겠습니다. 👏

2020-06-06 09:08 UTC, hwookim reviewed
안녕하세요 학성! 우입니다. 작성하신 유저 시나리오 잘 읽었어요.
시나리오를 읽고 몇 가지 든 생각이에요. 한번 확인해주세요!

이 서비스의 강점은 질문과 답변의 데이터베이스화라고 생각합니다.
데이터를 단순하게 저장할 뿐 아니라, 해당 데이터를 이용하여 분석된 통계를 서비스 내에서 보여주는 것도 시나리오에 녹여보면 어떨까요?

강사가 질문을 올리면 청중들은 아마 핸드폰으로 서비스에 접근할 것 같은데요.
모두가 핸드폰만 쳐다본다면 강연의 흐름이 끊기거나 시나리오처럼 분위기가 싸해질 수 있지 않을까요?
간단한 투표라면 실시간으로 그래프를 보여준다거나, 주관식 질문이라면 실시간으로 올라오는 답변을 하나씩 보여주는 것도 괜찮을 것 같네요.
해당 화면을 프로젝터에 연결하여 질문의 답을 받는 동안에도 강사가 지속해서 청중들과 소통할 수 있도록요!

2020-06-06 09:08 UTC, hwookim commented on README.md
> +## 정황 시나리오
서비스 사용에 대한 시나리오가 없는 점이 아쉽네요.
강사는 어떤 방식으로 서비스를 공유하고, 학생들은 어떤 방식으로 접근할 수 있을까요?

서비스를 실제 개발했다고 가정하고 그걸 사용하는 시나리오를 작성해보시는건 어떨까요?

2020-06-06 14:19 UTC, ordinCode commented
> 안녕하세요 학성! 만나서 반가워요~~
> 학성이 작성한 시나리오 잘 읽어봤습니다. :)
> 우선 반응이 없는 청중들의 생각과 반응을 얻기 위해서 서비스를 만드는 아이디어가 좋은 것 같아요. 어떻게든 청중들의 생각을 알고나면 강의를 진행할 방향을 더 쉽게 잡을 수 있을 것 같아요. 그리고 자주 할 질문에 대해서 기억에 의존하지 않고 데이터로 남기는 것이 특히 좋았던 것 같아요. :)
> 
> 그런데 저는 그러면 강의를 듣는 학생들은 `강사가 답변을 얻기 위해 강의마다 이 어플을 깔아야하는 것인가?` 하는 궁금증이 생겼어요. 강사에게는 분명히 큰 도움이 될 어플인데 학생들의 입장에서는 설치를 할 이유가 적어보였어요. 그래서 `어떻게 응답자들이 답변을 하게 만들 것인지`에 대해서 고민해보면 좋을 것 같습니다! :)

2020-06-06 15:26 UTC, ordinCode commented on README.md
> +## 요구사항 도출
처음 생각했던 그림은 일단 웹어플리케이션을 생각했고 해당 사이트로 접속해서 간단하게 버튼으로 의사(?)를 표현하는 그림이었습니다.(익명으로 말이죠)
그런데 두강이 말한 기능도 참고해서 여러가지 기능을 제공해주는 것도 좋을 것 같네요. 학교같은데서도 사용할 수 있도록이요! 참고해보겠습니다 감사합니다😄

2020-06-06 15:27 UTC, ordinCode commented on README.md
> +## 정황 시나리오
👍👍
시나리오와 기능 요구사항을 대대적으로 한번 수정해 봤어요!

2020-06-07 11:14 UTC, joseph415 approved these changes
안녕하세요 학성😀
한번 변경된 시나리오라서 잘 정리되고 세세한 부분까지 잘 나타난 것 같네요!

몇가지 생각해 볼 점이 있는것 같아서 의견을 남겨볼께요!

해당 서비스를 사용한다고 생각했을때 학생들은 링크를 타고 들어가 로그인을 하는지 안하는지에 대해서 나와있지 않은것 같아서 그부분도 궁금하네요

그리고 실제 이런 서비스를 대학교 강의 시간에 이용해본적이 있습니다. 그때는 간단한 로그인후 익명으로 진행했었는데요

익명으로 진행하다보니 약간 장난끼 있는 친구들이 수업에 상관없는 장난스런 의견을 내는 부분도 있더라구요 이런 부분에 대해서도 생각해 보면 좋을것 같아요!

실제로 만들어 진다면 좋은 서비스가 될 것 같네요😀

간단한 의견남겼으니 참고 해주시면 좋을 것 같아요.
저는 approve 하겠습니다. 고생하셨습니다😀

2020-06-08 01:19 UTC, ParkDooWon approved these changes
안녕하세요 학성!
저번에 질문드린 것에 친절하게 답변해주셔서 이해가 잘 됐어요. :)
밀씀하신대로 웹 어플리케이션으로 투표를 하는 방법이면 간단하게 진행할 수 있을 것 같네요.
멋진 서비스 기대하겠습니다! 수고하셨어요~~

2020-06-08 05:48 UTC, hwookim approved these changes
새 시나리오도 잘 읽었습니다!
개인적인 생각으로, 이 서비스의 가장 큰 숙제는 취합한 데이터를 유의미한 통계로 변환하는 과정이 될 것 같아요.
응답자의 연령대나 지역 등을 입력받아 통계에 녹여내는 방식을 적용하는 것도 좋을 것 같군요.

투표의 종류도 좀 더 확장해 활용성을 높여도 괜찮을 것 같습니다.
익명/기명의 선택이나 예/아니오/기타뿐만 아니라 설문과 같이 응답의 종류를 확장할 수 있는 식으로요.
강연에 초점을 맞춰 생각한다면, 강사는 필요한 질문들을 미리 만들어 저장하고 해당 URL에 접근할 수 있게 할 수도 있고, 강연 도중 필요해진 간단한 질문들은 서비스에서 제공하는 템플릿에 맞춰 빠르게 제작/공유할 수도 있는 방식은 어떨까요.

강사의 입장에서는 강연의 전체적인 소감을 받고 싶을 수 있으니 강연 막바지에 설문을 공유하고 후에 통계를 취합하는 방식도 좋겠네요. 강연의 보완이라는 목적에는 간단한 응답보다는 피드백이 포함된 설문이 부합한 것 같아요.
물론 설문 참여 유도는 강사의 몫이 되겠지만요.

제 의견은 이 정도인 것 같아요.
삶에 유용한 서비스 기대합니다!
이만 approve 할게요~

2020-06-09 06:40 UTC, Wonmi91 requested changes
안녕하세요 학성. 워니입니다 :)
강사들의 질문에 답변하기를 두려워하는 사람들을 위해서, 그리고 강사들도 즉각적으로 대답을 받을 수 있다는 점에서 좋은 것 같아요. 😊

하지만 어떤 의도로 이 기획을 하게 됐는지, 어떤 서비스를 운영하고 싶은 건지 간략하게 기획 의도/서비스 설명 등이 추가되면 좋을 것 같아요. 바로 유저 시나리오로 넘어가니까 바로 이해하기에는 조금 시간이 걸렸어요. 

추가적으로, 이 어플을 사용하게 될 주체는 둘일 텐데요. 강사와, 청중. 청중에 대한 시나리오를 따로 한 번 작성해 보시는 게 좋을 것 같습니다. 거기에서 새롭게 도출되는 요구 사항/기능 사항 등이 있을 것이니까요. 
강사용 관리 페이지/청중용 투표 페이지 둘 다 필요할 수도 있겠네요.
질문에 대한 결과를 함께 공유하는 서비스로 만들 것인지, 강사만을 위한 서비스로 만들 것인지도 고민해보시면 좋을 것 같아요. 정말 단순하게 답변만 하게 할 것인지, 쌍방향 소통을 위해서 질문을 남기거나, 설문을 주고받는 용도로도 사용하게 될 것인지 등등 서비스 확장성을 고려해보세요. 
이 서비스의 좋은 점은 데이터를 저장할 수 있다는 점일 텐데요. 이 정보를 어떻게 가공해서 보여줄지 조금 더 고민해보면 좋겠네요. 정말 실질적으로 다음 강의를 준비할 때 토대가 될 수 있도록 :)

2020-06-09 09:01 UTC, Wonmi91 approved these changes
투표 서비스가 강사와 청중 모두에게 도움이 되는 서비스가 되었으면 좋겠네요 :)
고생하셨어요. 이만 merge 하겠습니다 😊

2020-06-09 09:01 UTC, merged