[그니] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #26
Opened 2020-06-04 10:58 UTC by KueNiYam

다들 잘 부탁드려요. ㅎㅎ

2020-06-05 06:13 UTC, woonjangahn approved these changes
안녕하세요 그니! 요구사항에 맞게 잘 구현해주셨네요 💯 💯 

제 여동생이 매일 친구들과 행아웃으로 그림을 그리는게 취미라서 더 재미있게 읽었어요.
실시간으로 그림을 함께 그리고 이를 공유한다는 것은 새로운 경험이나 취미가 될 것 같네요.
[픽셀 페인터](https://store.steampowered.com/app/648120/Pixel_Painter/?l=koreana)나 [파스포투트](https://store.steampowered.com/app/582550/Passpartout_The_Starving_Artist/?l=koreana)가 생각이 났는데, 예술적인 느낌의 어떤 전시회 같은 느낌의 웹서비스라면 정말 컨셉에 맞는 매력적인 서비스가 될 것 같아요.

재밌는 기획 잘 읽고 갑니다!
이만 Approve 할게요 고생하셨습니다 :)

2020-06-06 07:56 UTC, lowoon approved these changes
안녕하세요 그니! 로운입니다.
아이디어가 굉장히 참신했어요! 😲 

미술 학원에서 취미로 한달정도 배운적이 있는데 굉장히 재밌었습니다.
이런 부분들을 어떻게 어필해서 사용자들이 참여하게 할지, 대회나 전시 등으로 참여자들을 어떻게 끌여들일지 궁금하네요.
그림을 잘 못그리는 사람들을 위해 기본적인 틀이 제공되는 경우도 있으면 좋을 것 같고, 마우스를 이용하기보단 태블릿과 펜을 이용해서 그리는 것에 좀 더 특화될 것 같은데 이러한 부분을 어떻게 구현할지 기대되네요.

미션하느라 고생하셨습니다 :) 이만 approve 할게요!

2020-06-08 01:00 UTC, YejiAhn approved these changes
안녕하세요, 그니! 요구사항에 맞게 잘 기획해주셨네요 😀
구글독스에서 처음 서비스 주제 읽으면서 무슨 게임을 기획해주시나 했는데 그림 서비스였군요!
그림 그리기 좋아하는 사람들에게 만족감과 재미를 주는 정말 좋은 서비스일 것 같다는 생각을 했어요.
주제를 준다고 하셨는데 주제 별 추천 상위 랭킹으로 작은 온라인 전시를 열어도 재밌을 것 같다고 생각했고,
가끔씩 사생대회? 경연대회?를 열어도 재미있을 것 같네요 ㅎㅎ 나중 얘기지만요!
재미있는 아이디어 잘 읽었습니다 이만 approve 할게요 : )

2020-06-08 01:43 UTC, KS-KIM commented
안녕하세요 그니⚾️, 알트입니다! 미션 잘 작성하셨어요 👍👍

흥미로운 주제로 서비스를 기획하고 계시네요!
사용자를 구체화한다면 좋을 것 같습니다. 간단한 그림을 그리길 원하는 라이트 유저한테는 간단한 인터페이스가 더 맞을 것 같고, 그림을 많이 그려본 헤비 유저는 포토샵과 같은 다양한 그리기 도구 인터페이스가 적합할 것 같아요. 다양한 유저층을 포용하는 것은 어려울 수도 있는데, 적절한 해결법을 찾는다면 재밌는 서비스가 탄생할 것 같아요!

고생하셨습니다! 이만 Approve 할게요😊

2020-06-08 01:44 UTC, KS-KIM approved these changes
안녕하세요 그니⚾️, 알트입니다! 미션 잘 작성하셨어요 👍👍

흥미로운 주제로 서비스를 기획하고 계시네요!
사용자를 구체화한다면 좋을 것 같습니다. 간단한 그림을 그리길 원하는 라이트 유저한테는 간단한 인터페이스가 더 맞을 것 같고, 그림을 많이 그려본 헤비 유저는 포토샵과 같은 다양한 그리기 도구 인터페이스가 적합할 것 같아요. 다양한 유저층을 포용하는 것은 어려울 수도 있는데, 적절한 해결법을 찾는다면 재밌는 서비스가 탄생할 것 같아요!

고생하셨습니다! 이만 Approve 할게요😊

2020-06-09 02:47 UTC, pobiconan requested changes
저는 어린 시절의 아픈 추억 때문에 음악과 그림을 엄청 싫어하는데요.
이런 서비스가 등장하면 그림을 그리는데 좀 더 용기를 낼 수 있을까 기대되네요. 💯 

저와 같이 그림을 그리는데 두려움을 느끼는 사람이나, 혼자 그림을 그리지만 누군가에게 공유하는 것을 좋아하는 사람들 입장에서도 한번 고민해 보면 어떨까요?
현재 우테코의 짝 프로그래밍과 같이 수평관계가 아닌 가르치고/배우는 상황도 있을 것 같은데요.

2020-06-09 15:05 UTC, KueNiYam commented
다들 좋은 의견 감사합니다!!! 
현재 기획안은 직관적이면서 세련된 사용자 경험을 배경으로 하나의 강력한 기능(오픈 캔버스 서비스)을 구현하여 서비스를 오픈한 뒤 추후 추가적인 기능들을 점진적으로 개발하려고구상하고 있습니다.
 - 예술적인 전시회 같은 느낌의 웹서비스(호들)
 - 그림을 그리는데 도움이 되는 툴(로운)
 - 랭킹 별 전시 혹은 대회(예지니어스)
 - 라이트 유저와 헤비 유저 각각에 걸맞는 인터페이스 제공(알트)
 - 그림을 그리는데 두려움을 느끼는 사람이나, 혼자 그림을 그리지만 누군가에게 공유하는 것을 좋아하는 사람을 위한 서비스 and 짝 프로그래밍과 같이 수평관계가 아닌 가르치고/배우는 상황에 대한 서비스(포비)

 등 좋은 의견들 감사합니다..! 후에 서비스를 개발하게 된다면 의견들을 받아들여 점진적인 확장을 시도해보겠습니다..!!

2020-06-09 23:15 UTC, pobiconan approved these changes
포비를 40세로 표현해 주다니 무한 감동이 ㅠㅠ 
저와 같이 그림 그리는 것에 두려움을 느끼는 사람들도 그림에 도전할 수 있는 용기를 줄 수 있는 서비스가 되기를...

2020-06-09 23:15 UTC, merged