[제이미] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #35
Opened 2020-06-04 14:30 UTC by jamie9504

[이곳](https://github.com/jamie9504/woowa-userstory-2020/tree/userStory)에서 더 예쁘게 보실 수 있어요! :)

감사합니다~!

2020-06-04 15:03 UTC, Hamliet reviewed
실제로 상용화가 될 것 같은 서비스네요!
짧은 코멘트 하나 남겼습니다! 확인부탁드려요~!

2020-06-04 15:03 UTC, Hamliet commented on README.md
> + 비건, 할랄, 어린이메뉴 여부, 저염식, 저탄고지 등 사용자의 食에 대한 니즈가 다양해진 현재, 식당을 한 번 가려고 하면 지도를 통해 조건을 하나씩 다 찾아봐야 하는 불편함이 있습니다. 이에 니즈가 녹아있는 食지도가 있으면 편할 것 같다는 생각이 들었고,  가게에서 작성해줘도 좋고, 그렇지 않다면 소비자들이 직접 참여해서 만들어가는 "함께 채워가는 食
실제로 수요가 많은 서비스가 될 것 같네요!

2020-06-04 15:03 UTC, Hamliet commented on README.md
> +### 요구사항
위에 시나리오에서 나왔던 여러 요구사항들을 포함하면 좋을 것 같아요! (블라인드 처리,  공유기능 등)

2020-06-04 15:05 UTC, aegis1920 reviewed
안녕하세요 제이미! 빙봉입니다 :)
이 서비스는 말 그대로 먹는 것에 대한 니즈를 잘 파악하고 선택해야 할 것 같아요!
코멘트 남겼으니 확인해주세요!

2020-06-04 15:05 UTC, aegis1920 commented on README.md
> +- 대분류로 식당을 구분할 수 있어야 한다.
대분류가 서비스 전체의 니즈를 말해주는 만큼 잘 생각해봐야할 것 같아요!

2020-06-04 15:05 UTC, aegis1920 commented on README.md
> +- 대분류를 선택하면, 상세 분류를 선택할 수 있고 상세 분류로도 식당을 구분할 수 있어야 한다.
상세 분류도 경우의 수가 많아 잘 생각해보고 선택해야할 것 같네요 :)

2020-06-04 15:05 UTC, aegis1920 commented on README.md
> + 올바른 음식을 추천해주지 않았다는 생각에 기분이 오묘해졌던 그는, 맨 위 상단의 '해당 자료는 100% 정확하지 않을 수 있으니 필요시 가게에 확인을 꼭 부탁드립니다.'라는 문구를 읽고 문구를 꼼꼼히 읽지 않음을 반성했다.
세심하네요 👍

2020-06-05 11:05 UTC, yebink reviewed
안녕하세요 제이미!
실제로 있으면 많이 이용할 것 같은 서비스네요 🙂 
 
몇 가지 코멘트 추가했으니 참고해주세요!

2020-06-05 11:05 UTC, YebinK commented on README.md
> +- 대분류로 식당을 구분할 수 있어야 한다.
식당을 구분하는 기준을 더 다양하게 두면 좋을 것 같아요!
ex. 분위기, 프라이빗한 룸이 있는지 여부, 사람이 많은지 여부 등!

식당 데이터를 모으는 것이 관건일 것 같아요!
이 부분에 대한 구체적인 계획이 있으면 좋을 것 같네요.

2020-06-05 11:05 UTC, YebinK commented on README.md
> + 비건, 할랄, 어린이메뉴 여부, 저염식, 저탄고지 등 사용자의 食에 대한 니즈가 다양해진 현재, 식당을 한 번 가려고 하면 지도를 통해 조건을 하나씩 다 찾아봐야 하는 불편함이 있습니다. 이에 니즈가 녹아있는 食지도가 있으면 편할 것 같다는 생각이 들었고,  가게에서 작성해줘도 좋고, 그렇지 않다면 소비자들이 직접 참여해서 만들어가는 "함께 채워가는 食
이미 존재하는 "망고플레이트"같은 맛집 어플과 차별점이 무엇인지 좀 더 명확히 해두면 좋을 것 같아요!

2020-06-07 06:28 UTC, dks301 reviewed
안녕하세요 제이미!

활성화만 된다면 정말 좋은 서비스 같아요 👍 
몇 가지 코멘트 남겼으니 반영해주세요~

2020-06-07 06:28 UTC, dks301 commented on README.md
> + 비건, 할랄, 어린이메뉴 여부, 저염식, 저탄고지 등 사용자의 食에 대한 니즈가 다양해진 현재, 식당을 한 번 가려고 하면 지도를 통해 조건을 하나씩 다 찾아봐야 하는 불편함이 있습니다. 이에 니즈가 녹아있는 食지도가 있으면 편할 것 같다는 생각이 들었고,  가게에서 작성해줘도 좋고, 그렇지 않다면 소비자들이 직접 참여해서 만들어가는 "함께 채워가는 食
활성화되기 전까지는 어떻게 사용자들이 지도를 작성하도록 유도할지가 핵심인 것 같아요
이 부분에 대해 생각해보면 좋을 것 같아요 :)

2020-06-07 06:28 UTC, dks301 commented on README.md
> +- 메뉴에 올바르지 못한 태그, 판매하지 않는 메뉴 등은 블라인드할 수 있다.
악의적인 블라인드에 대한 신고기능 같은 것도 추가해야하지 않을까요 ?

2020-06-07 13:09 UTC, jamie9504 reviewed
코멘트 주신 부분 수정해보았습니다~!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> +- 대분류로 식당을 구분할 수 있어야 한다.
분류를 등록할 수 있는 화면도 있으면 좋을 것 같네요!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> +- 대분류를 선택하면, 상세 분류를 선택할 수 있고 상세 분류로도 식당을 구분할 수 있어야 한다.
상세 분류도 등록 기능이 있으면 좋겠네요!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> +- 대분류로 식당을 구분할 수 있어야 한다.
식당 구분 기준의 경우엔 분위기/사람이 많은지 여부의 경우 주관적이 될 수 있어서
객관적인 개별룸이 있는지 여부정도가 있으면 좋을 것 같아요!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> +- 메뉴에 올바르지 못한 태그, 판매하지 않는 메뉴 등은 블라인드할 수 있다.
추가해보았습니다~!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> +### 요구사항
네~ 추가해두었습니다!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> + 비건, 할랄, 어린이메뉴 여부, 저염식, 저탄고지 등 사용자의 食에 대한 니즈가 다양해진 현재, 식당을 한 번 가려고 하면 지도를 통해 조건을 하나씩 다 찾아봐야 하는 불편함이 있습니다. 이에 니즈가 녹아있는 食지도가 있으면 편할 것 같다는 생각이 들었고,  가게에서 작성해줘도 좋고, 그렇지 않다면 소비자들이 직접 참여해서 만들어가는 "함께 채워가는 食
추가해보았습니다!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> +- 대분류로 식당을 구분할 수 있어야 한다.
데이터를 모으는 것에 대해서는 조금 고민해서 아래에 추가해보았습니다!

2020-06-07 13:09 UTC, jamie9504 commented on README.md
> + 비건, 할랄, 어린이메뉴 여부, 저염식, 저탄고지 등 사용자의 食에 대한 니즈가 다양해진 현재, 식당을 한 번 가려고 하면 지도를 통해 조건을 하나씩 다 찾아봐야 하는 불편함이 있습니다. 이에 니즈가 녹아있는 食지도가 있으면 편할 것 같다는 생각이 들었고,  가게에서 작성해줘도 좋고, 그렇지 않다면 소비자들이 직접 참여해서 만들어가는 "함께 채워가는 食
데이터를 모으는 것에 대해서는 조금 고민해서 아래에 추가해보았습니다!

2020-06-07 17:30 UTC, yebink reviewed
안녕하세요 제이미! 아이디어가 훨씬 발전했네요! 💯 
커스텀 분류 등록 기능이 인상적이에요!
한 가지 궁금한 점이 있어 추가 코멘트 달았어요.
수고하셨어요 이만 머지할게요~

2020-06-07 17:30 UTC, YebinK commented on README.md
> +  - 반대로 10개 이상 비추천시 자동 블락되며, 승인시 제거된다.
커스텀 분류 등록 기능이 인상적이네요! 👍 
형식에 구애받지 않는 것이 아주 참신하고 좋아요.

2020-06-07 17:30 UTC, YebinK commented on README.md
> +- 메뉴를 등록할 수 있다.
광고나 홍보 목적으로 특정 업체의 메뉴 리뷰를 등록하는 경우도 발생할 것 같은데요!
혹시 이 부분을 의도한 것이 아니라면, 대책이 필요해 보이네요!

2020-06-08 00:23 UTC, dks301 approved these changes
안녕하세요 제이미!
반영 잘해주셨네요 👍 
수고하셨습니다 approve 할게요~

2020-06-08 01:06 UTC, Hamliet approved these changes
안녕하세요 제이미. 피드백 반영 잘 하셨네요!
Approve 하겠습니다. 수고하셨어요!! 😀

2020-06-08 01:15 UTC, yebink approved these changes

2020-06-08 02:16 UTC, aegis1920 approved these changes
안녕하세요 제이미! 빙봉입니다 :)
피드백 반영을 세심하게 잘해주셨네요 👍 
아주 간단한 피드백 하나를 추가했는데 구현되고 나서 충분히 바꿀 수 있는 부분이라 approve해도 될 것 같아요 💯 
수고하셨습니다!

2020-06-08 02:16 UTC, aegis1920 commented on README.md
> +- 해당 태그, 메뉴 등의 블라인드 요청이 N개 이상시 완전 삭제된다.
피드백 반영 굿굿 👍

2020-06-08 02:16 UTC, aegis1920 commented on README.md
> +  - 등록 신청된 경우, 10개 이상 추천시 자동 등록되며, 승인시 수동 등록된다.
개인적으로는 10개라는 기준을 조금 늘려도 괜찮을 것 같아요 :)
어떤 단체가 마음을 나쁘게 먹으면 충분히 커스텀 등록을 할 수 있어보이네요

2020-06-08 02:22 UTC, jamie9504 commented on README.md
> +  - 등록 신청된 경우, 10개 이상 추천시 자동 등록되며, 승인시 수동 등록된다.
신고가 들어오면 이도 블라인드나 내리기가 되기 때문에, 일단 기준 갯수를 10개로 했는데
조금 더 고민해봐야할 것 같습니다!

의견 감사해요!

2020-06-08 02:26 UTC, jamie9504 commented on README.md
> +- 메뉴를 등록할 수 있다.
객관적인 지표들만 등록이 가능하다고 가정하고 있기 때문에,
특정 업체의 메뉴를 등록하는 경우는 상관 없습니다!

오히려 점주들이 직접 등록하는 것도 권장하려 하구요!
오등록이 많이 발생하는 경우 경고/강퇴를 통해 관리하려 합니다!

2020-06-08 06:44 UTC, wmakerjun requested changes
안녕하세요 🕺준이에요 ㅎㅎ
너무 멋진 아이디어에요 👍 
저도 개인적으로 6개월정도 채식했던 기간이 있었는데, 그 때 이 서비스가 있었다면 더 오래 했었을 거란 생각이 드네요 ㅎㅎ
이미 다른 크루들이 좋은 피드백 많이 남겨주고, 반영해줘서 몇가지만 간단하게 남겼습니다!

2020-06-08 06:44 UTC, eastjun commented on README.md
> + 기존 맛집 어플의 경우 "분위기", "맛"에 치중된 어플이라면 食지도의 경우 조금 다른 시각에서 접근되는 '재료', '어린이 동석가능 여부', '필요 영양소 충족' 등의 주제들을 다룰 수 있는 어플입니다. 또한, 이 부분을 혼자 만들어가는 것이 아닌 같은 취향을 가진 사람들과 공유하며 채워나가는 어플입니다.
`어린이 동석가능 여부`라는 옵션과 `채식`, `할랄`이 카테고리가 다르다는 생각이 들어요. 추가적으로 `어린이 동석가능 여부`는 옵션이 있다면 당연히 좋지만, 처음에 보다 명확한 서비스의 아이덴티티를 위해서 `채식`, `할랄`에 집중하는건 어떨까요?

2020-06-08 06:44 UTC, eastjun commented on README.md
> +- 해당 앱이 과연 지속(유지보수)될 수 있는가?
해당 앱이 능동적으로 지속이 되려면, 메뉴의 등록, 메뉴의 검열을 유저들이 진행해야 가능할 것 같아요. 그런데 유저의 특징이 본인의 식사에 대해 아무래도 고려할 게 많은 유저들이다보니, 그들에게 어떤 보상책을 주느냐에 따라 굉장히 능동적이고, 충성도가 높은 유저층이 될 것 같아요 보상으로 어떤걸 부여할 수 있을까요?

2020-06-08 06:44 UTC, eastjun commented on README.md
> +#### 블라인드(상세)
꼼꼼한 블라인드 정책에 대한 고민이 돋보여요!!! 👍👍👍

2020-06-08 06:44 UTC, eastjun commented on README.md
> +- 메뉴에 태그를 달 수 있다.
태그 단거는 나중에 어떻게 활용되나요?

2020-06-09 07:17 UTC, jamie9504 reviewed
꼼꼼한 리뷰 감사합니다 :)

2020-06-09 07:17 UTC, jamie9504 commented on README.md
> +- 해당 앱이 과연 지속(유지보수)될 수 있는가?
고민을 해보았는데, (일단 비금전적으로..)

기여도별로 랭킹을 세워둬서 명예보상...? 같은 걸 부여할 수도 있을 것 같구요!
뭔가 신뢰도가 오르면, 데이터를 등록하고 블라인드를 하고, 신고를 할 때 권한을 조금 더 쎄게..? (신고/블라인드/등록시 일반 사용자의 *2배 효과..?) 해도 되지 않을까 싶은데 지금 떠오르는건 많이 없네요 :)

2020-06-09 07:17 UTC, jamie9504 commented on README.md
> +- 메뉴에 태그를 달 수 있다.
태그는 세부 카테고리를 태깅해두든거고, 나중에 지도에서 세부 카테고리로 검색할 때 도움이 됩니당 :)

2020-06-09 07:17 UTC, jamie9504 commented on README.md
> + 기존 맛집 어플의 경우 "분위기", "맛"에 치중된 어플이라면 食지도의 경우 조금 다른 시각에서 접근되는 '재료', '어린이 동석가능 여부', '필요 영양소 충족' 등의 주제들을 다룰 수 있는 어플입니다. 또한, 이 부분을 혼자 만들어가는 것이 아닌 같은 취향을 가진 사람들과 공유하며 채워나가는 어플입니다.
훔.. 고민인데 일단 채식, 할랄에 집중해서 홍보하는 것도 좋은 것 같아요!

의도는 약간 유저들이 만들어가는 편의성(?) 짙은 서비스가 되고 싶어서, 여러가지를 넣어본 건데 집중 타겟을 선 공략하는 것도 좋은 것 같습니다.
카테고리는 다다익선이라고 생각해서 (결국 유저들이 추가가 가능하긴 하니까) 홍보에는 채식, 할랄 정도만 넣어도 될 것 같네요~!

2020-06-09 08:12 UTC, eastjun commented
개인의 성향에 초점을 맞춰서 세심한 배려가 돋보이는 서비스 고민하고 발전시키느라 너무 고생했습니다 👍 
더욱 빛나는 아이디어와 서비스가 되길 바라며 merge할게요 😄

2020-06-09 08:12 UTC, wmakerjun approved these changes

2020-06-09 08:12 UTC, merged