[소니] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #40
Opened 2020-06-04 15:58 UTC by sonypark

[여기](https://github.com/sonypark/woowa-userstory-2020/tree/scenario-userstory)에서 보실 수 있습니다.

2020-06-05 13:05 UTC, toneyparky approved these changes
소니소니 반가워요😃

글쓰기 때도 그렇고 소니의 글은 잘 읽히네요.

구직을 하는 개발자에게 꼭 필요한 서비스 기획 잘 봤습니다.

적절한 벤치마킹으로 차별화된 서비스를 만들 수 있을거같아요!

다만 강력한 대체제인 오픈 카톡방보다 소니의 서비스를 이용하게할 방법에 대해 생각해보면 좋겠네요!

주말 동안 더 발전한 서비스 기대할게요😊

2020-06-05 13:05 UTC, toneyparky commented on README.md
> +현재 진행중인 개발자 채용 공고 위주로 채팅방을 만들고, 채팅방에서 지원자들끼리 정보를 공유하는 플랫폼 서비스입니다. 채팅은 게시글을 올리거나 메일을 보내는 것보다 부담이 덜 하기 때문에, 지원자들이 부담없이 접근해서 자유롭게 질의 응답할 것으로 기대됩니다.
현재 진행중인 개발자 채용 공고 정보를 어떠한 방법으로 모을지 기대되는군요..!

크롤러를 만드려나요? 유저가 직접 채팅방을 만드는 방법도 있겠네요!

2020-06-05 13:05 UTC, toneyparky commented on README.md
> +기본 포맷은 원티드나 로켓펀치와 비슷하게 개발자 채용에만 특화된 채용 공고 사이트입니다. 여기에 자소설 닷컴에 있는 채팅방 기능을 추가하려고 합니다. (덧, 자소설 닷컴 채팅방은 각 공고별 지원자들끼리 채팅방을 통해 소통하는 공간입니다.)
자소설 닷컴을 사용하는 친구를 봤는데 다른 기능보다 채팅기능에서 얻는 정보가 많다더라구요. 
이를 벤치마킹하는거 좋다고 생각해요😁

2020-06-05 13:05 UTC, toneyparky commented on README.md
> +    - 현재 진행중인 개발자 채용/교육 공고 위주 채팅방 생성
요즘에는 공고가 생기면 오픈 카톡방이 자연스레 생기더라구요.
오픈 카톡방과 차별화 되는 부분이 필요할 거 같아요😀

2020-06-05 13:05 UTC, toneyparky commented on README.md
> +- 온오프라인 코딩테스트 수준과 준비하기 위한 방법을 알고 싶다.
열린 공고의 이전 분기 코테 후기라던가, 문제 혹은 면접 내용에 대한 정보를 제공해주면 오픈 카톡방과 차별화를 시킬 수 있겠네요!

2020-06-05 13:05 UTC, toneyparky commented on README.md
> +- 함께 면접을 준비할 스터디원을 구하고 싶다.
1:1 쪽지 이외에도 스터디를 조직하는 기능도 추가되면 서비스에 머물 이유가 늘어날 거 같군요.

2020-06-05 13:05 UTC, toneyparky commented on README.md
> +|채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다.|- 어뷰징 유저를 신고할 수 있는 버튼이 있어야 한다. <br> - 5회 이상 신고가 누적되면 해당 채팅방에서 강제 퇴장 당해야 한다. <br> - 신고 누적으로 강제 퇴장 당한 유저는 해당 채팅방에 일주일 간 접속할 수 없어야 한다.|
악의로 5인이 짜고 사람들을 퇴장시킬 수 있다고 생각해요.
지속적으로 동일한 5인이 사용자를 퇴장시킬 경우에 대해서는 예외처리를 주는 방법도 고려해볼 수 있겠네요.

2020-06-06 03:31 UTC, KimGyeong approved these changes
안녕하세요 소니! 첫 인사를 깃헙으로 드리게 되네요😂

다른 서비스들과의 차이점을 확실하게 가져가는 것이 가장 중요할 것 같아요!

깔끔하게 작성하셔서 코멘트 두개만 남기고 Approve하겠습니다~

2020-06-06 03:31 UTC, hwangbo commented on README.md
> +현재 진행중인 개발자 채용 공고 위주로 채팅방을 만들고, 채팅방에서 지원자들끼리 정보를 공유하는 플랫폼 서비스입니다. 채팅은 게시글을 올리거나 메일을 보내는 것보다 부담이 덜 하기 때문에, 지원자들이 부담없이 접근해서 자유롭게 질의 응답할 것으로 기대됩니다.
공고 정보 수집과 더불어, 지원자임을 확인하는 기능도 필요할 것 같아요!

다른 목적을 가진 사용자가 참여를 하게 되면 문제가 생기지 않을까요?

2020-06-06 03:31 UTC, hwangbo commented on README.md
> +|채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다.|- 어뷰징 유저를 신고할 수 있는 버튼이 있어야 한다. <br> - 5회 이상 신고가 누적되면 해당 채팅방에서 강제 퇴장 당해야 한다. <br> - 신고 누적으로 강제 퇴장 당한 유저는 해당 채팅방에 일주일 간 접속할 수 없어야 한다.|
여러 차례 신고를 받은 사용자에 대한 대안도 필요할 것 같네요. 누적 강제 퇴장 수에 따른 규칙을 추가하는 것도 고려해보면 좋을 것 같아요.

2020-06-06 09:39 UTC, lalize approved these changes
소니~ 기획서 잘 읽었어요 😊
개발자 채용 공고와 채팅 기능을 합쳐서 한 곳에서 정보를 얻을 수 좋은 것 같아요!
그리고 다른 서비스와 확실한 차별화를 위해 좀 더 추가적으로 기능을 생각해볼 필요가 있을 것 같아요 🤔

2020-06-06 09:39 UTC, lalize commented on README.md
> +- 궁금한 점을 질문할 곳이 없다. 지인이 없는 경우 더더욱..
😭

2020-06-06 09:39 UTC, lalize commented on README.md
> +현재 진행중인 개발자 채용 공고 위주로 채팅방을 만들고, 채팅방에서 지원자들끼리 정보를 공유하는 플랫폼 서비스입니다. 채팅은 게시글을 올리거나 메일을 보내는 것보다 부담이 덜 하기 때문에, 지원자들이 부담없이 접근해서 자유롭게 질의 응답할 것으로 기대됩니다.
접근성이 뛰어난 건 좋지만, 서비스 의도와 상반되는 목적으로 사용할 가능성도 있겠네요.

2020-06-06 09:39 UTC, lalize commented on README.md
> +|합격한 익명의 지원자들은 2차 면접 예상 질문을 공유하고 있다.|- 채팅방에 입장한 유저들에게 익명 보장을 위한 랜덤 닉네임이 주어져야 한다. <br> - 채팅을 통해 실시간으로 메시지를 주고 받을 수 있어야 한다.|
지원자들이 정보만을 공유하면 좋은데 친목을 통해 방 분위기를 흐릴수도 있다고 생각해요.
시간을 두고 매번 닉네임을 랜덤하게 갱신하면 더 좋을 것 같아요.

2020-06-06 09:39 UTC, lalize commented on README.md
> +|김개발은 면접 스터디 할 사람이 있는지 물었고, 희망하는 사람은 1:1 쪽지를 달라는 메시지를 남겼다.|- 1:1 쪽지 기능이 있어야 한다.|
익명을 포기하게 되는군요...

2020-06-06 09:39 UTC, lalize commented on README.md
> +    - 현재 진행중인 개발자 채용/교육 공고 위주 채팅방 생성
채팅방에 다른 특수 기능이 존재하나요?!
그게 아니라면 다른 서비스와 차별화 하는 기능을 추가적으로 생각해봐야 할 것 같아요!

2020-06-06 09:39 UTC, lalize commented on README.md
> +|채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다.|- 어뷰징 유저를 신고할 수 있는 버튼이 있어야 한다. <br> - 5회 이상 신고가 누적되면 해당 채팅방에서 강제 퇴장 당해야 한다. <br> - 신고 누적으로 강제 퇴장 당한 유저는 해당 채팅방에 일주일 간 접속할 수 없어야 한다.|
어뷰징 유저의 채팅을 차단하는 기능도 추가하면 좋을 것 같네요.

2020-06-06 09:39 UTC, lalize commented on README.md
> +기본 포맷은 원티드나 로켓펀치와 비슷하게 개발자 채용에만 특화된 채용 공고 사이트입니다. 여기에 자소설 닷컴에 있는 채팅방 기능을 추가하려고 합니다. (덧, 자소설 닷컴 채팅방은 각 공고별 지원자들끼리 채팅방을 통해 소통하는 공간입니다.)
개발자 취업에 많은 영향을 줄 것 같아요~  😊

2020-06-06 11:44 UTC, ttkmw approved these changes
안녕하세요~
소니의 기획안 잘 읽었습니다!
최대한 피드백을 많이 달려고 했지만 감상 위주네요ㅎㅎ
고생하셨습니다~

2020-06-06 11:44 UTC, p-vibe commented on README.md
> +기본 포맷은 원티드나 로켓펀치와 비슷하게 개발자 채용에만 특화된 채용 공고 사이트입니다. 여기에 자소설 닷컴에 있는 채팅방 기능을 추가하려고 합니다. (덧, 자소설 닷컴 채팅방은 각 공고별 지원자들끼리 채팅방을 통해 소통하는 공간입니다.)
오 자소설 닷컴에도 채팅방이 있었군요...

2020-06-06 11:44 UTC, p-vibe commented on README.md
> +- 궁금한 점을 질문할 곳이 없다. 지인이 없는 경우 더더욱..
ㅠ_ㅠ

2020-06-06 11:44 UTC, p-vibe commented on README.md
> +    - 같이 준비하는 다른 지원자들과 이야기를 나누고 싶지만 그럴 수 있는 창구가 없다.
칭구로 읽고 ㅠ_ㅠ 한번 더할뻔했네요..

2020-06-06 11:44 UTC, p-vibe commented on README.md
> +채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다. 5명으로부터 신고당한 어뷰징 유저는 강퇴 당했다.
신고하기 기능은 카카오톡 오픈 채팅방에  있다는 말씀이신가요??
위 줄에서 이미 사람들이 오픈 채팅방에 이동했다고 해서, 헷갈렸습니다..!

2020-06-06 15:16 UTC, sonypark commented on README.md
> +기본 포맷은 원티드나 로켓펀치와 비슷하게 개발자 채용에만 특화된 채용 공고 사이트입니다. 여기에 자소설 닷컴에 있는 채팅방 기능을 추가하려고 합니다. (덧, 자소설 닷컴 채팅방은 각 공고별 지원자들끼리 채팅방을 통해 소통하는 공간입니다.)
네 저도 주변 친구들이 취준생일때 유용하게 사용했다는 후기를 듣고 아이디어를 떠올렸어요!ㅎㅎ😊

2020-06-06 15:16 UTC, sonypark commented on README.md
> +    - 현재 진행중인 개발자 채용/교육 공고 위주 채팅방 생성
그렇군요..ㅠㅠ 오픈카톡방을 써본 적이 없어서 몰랐네요.
차별화 할 부분을 생각해보겠습니다!

2020-06-06 15:17 UTC, sonypark commented on README.md
> +- 온오프라인 코딩테스트 수준과 준비하기 위한 방법을 알고 싶다.
오오 좋은 의견 감사합니다!!

2020-06-06 15:18 UTC, sonypark commented on README.md
> +- 함께 면접을 준비할 스터디원을 구하고 싶다.
이것도 좋은 의견이네요! 감사합니다👍

2020-06-06 15:19 UTC, sonypark commented on README.md
> +|채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다.|- 어뷰징 유저를 신고할 수 있는 버튼이 있어야 한다. <br> - 5회 이상 신고가 누적되면 해당 채팅방에서 강제 퇴장 당해야 한다. <br> - 신고 누적으로 강제 퇴장 당한 유저는 해당 채팅방에 일주일 간 접속할 수 없어야 한다.|
음 그럴수도 있겠네요. 참고하겠습니다!

2020-06-06 15:25 UTC, sonypark commented on README.md
> +현재 진행중인 개발자 채용 공고 위주로 채팅방을 만들고, 채팅방에서 지원자들끼리 정보를 공유하는 플랫폼 서비스입니다. 채팅은 게시글을 올리거나 메일을 보내는 것보다 부담이 덜 하기 때문에, 지원자들이 부담없이 접근해서 자유롭게 질의 응답할 것으로 기대됩니다.
네 저도 이 부분을 생각 해봤는데, 자소설닷컴 채팅방을 잘 활용하던 주변 친구들 이야기를 들어보면 관련 없는 사람이 들어와서 훼방(?)을 놓을 일은 많지 않은 것 같더라구요. 만약 채팅방에서 부적절한 용어를 사용하거나 목적과 관계없는 말을 하는 사용자는 신고하기 버튼으로 차단할 수 있게 할 예정입니다.

서비스가 자유롭게 정보를 공유하는 공간을 목적으로 하기에 실제 지원자에 한정해서 채팅방을 이용할 수 있게하기 보단, 지원은 안 했지만 관심 있는 사람들도 참여할 수 있도록 하는게 좋을 것 같다고 생각했습니다.😊

2020-06-06 15:26 UTC, sonypark commented on README.md
> +- 궁금한 점을 질문할 곳이 없다. 지인이 없는 경우 더더욱..
😢

2020-06-06 15:27 UTC, sonypark commented on README.md
> +기본 포맷은 원티드나 로켓펀치와 비슷하게 개발자 채용에만 특화된 채용 공고 사이트입니다. 여기에 자소설 닷컴에 있는 채팅방 기능을 추가하려고 합니다. (덧, 자소설 닷컴 채팅방은 각 공고별 지원자들끼리 채팅방을 통해 소통하는 공간입니다.)
네 주변에 공채 준비하는 지인들이 자소설닷컴 채팅방이 꽤 도움이 되었다고 하더라구요.

2020-06-06 15:28 UTC, sonypark commented on README.md
> +- 궁금한 점을 질문할 곳이 없다. 지인이 없는 경우 더더욱..
😭

2020-06-06 15:28 UTC, sonypark commented on README.md
> +    - 같이 준비하는 다른 지원자들과 이야기를 나누고 싶지만 그럴 수 있는 창구가 없다.
ㅋㅋㅋㅋㅋㅋ 그럼 정말 슬프네요..

2020-06-06 15:29 UTC, sonypark commented on README.md
> +채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다. 5명으로부터 신고당한 어뷰징 유저는 강퇴 당했다.
앗 헷갈릴 수 있겠네요! 헷갈리지 않도록 수정하겠습니다. 😅

2020-06-06 15:30 UTC, sonypark commented on README.md
> +|채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다.|- 어뷰징 유저를 신고할 수 있는 버튼이 있어야 한다. <br> - 5회 이상 신고가 누적되면 해당 채팅방에서 강제 퇴장 당해야 한다. <br> - 신고 누적으로 강제 퇴장 당한 유저는 해당 채팅방에 일주일 간 접속할 수 없어야 한다.|
네 좋은 의견이네요. 1차 신고의 경우 메시지를 가리고, 2차 신고의 경우 강퇴를 하는 방향도 괜찮을거 같아요!! 감사합니다.👍

2020-06-06 15:34 UTC, sonypark commented on README.md
> +|김개발은 면접 스터디 할 사람이 있는지 물었고, 희망하는 사람은 1:1 쪽지를 달라는 메시지를 남겼다.|- 1:1 쪽지 기능이 있어야 한다.|
아뇨 1:1 쪽지도 익명 보장을 유지하려고 합니다! 😄

2020-06-06 15:41 UTC, sonypark commented on README.md
> +|합격한 익명의 지원자들은 2차 면접 예상 질문을 공유하고 있다.|- 채팅방에 입장한 유저들에게 익명 보장을 위한 랜덤 닉네임이 주어져야 한다. <br> - 채팅을 통해 실시간으로 메시지를 주고 받을 수 있어야 한다.|
닉네임 랜덤 갱신이라! 자칫하면 혼란을 줄 수도 있다는 걱정도 됨과 동시에 친목 도모 방지를 위한 좋은 기능인 것 같에요. 의견 감사합니다~👍

2020-06-06 15:47 UTC, sonypark commented on README.md
> +현재 진행중인 개발자 채용 공고 위주로 채팅방을 만들고, 채팅방에서 지원자들끼리 정보를 공유하는 플랫폼 서비스입니다. 채팅은 게시글을 올리거나 메일을 보내는 것보다 부담이 덜 하기 때문에, 지원자들이 부담없이 접근해서 자유롭게 질의 응답할 것으로 기대됩니다.
그쵸. 어딜가나 악용하는 사람은 있죠.ㅠㅠ

2020-06-06 15:49 UTC, sonypark commented on README.md
> +|채팅방에서 욕설을 한 유저가 있어 신고하기 버튼을 눌러 신고했다.|- 어뷰징 유저를 신고할 수 있는 버튼이 있어야 한다. <br> - 5회 이상 신고가 누적되면 해당 채팅방에서 강제 퇴장 당해야 한다. <br> - 신고 누적으로 강제 퇴장 당한 유저는 해당 채팅방에 일주일 간 접속할 수 없어야 한다.|
네 좋은 의견 감사합니다! 누적 신고된 사용자에 한 해 페널티 기능도 고려해보겠습니다 :)

2020-06-07 03:26 UTC, sonypark commented on README.md
> +기본 포맷은 원티드나 로켓펀치와 비슷하게 개발자 채용에만 특화된 채용 공고 사이트입니다. 여기에 자소설 닷컴에 있는 채팅방 기능을 추가하려고 합니다. (덧, 자소설 닷컴 채팅방은 각 공고별 지원자들끼리 채팅방을 통해 소통하는 공간입니다.)
그랬으면 좋겠네요~😆

2020-06-07 03:56 UTC, sonypark commented on README.md
> +    - 현재 진행중인 개발자 채용/교육 공고 위주 채팅방 생성
카카오 오픈 채팅방과의 차별점?

- 카카오 채팅방의 단점
    1. 해당 채팅방에 들어가기 위해 직접 검색 해야한다.
        - 검색하기전에는 해당 채팅방이 있는지 알 수 없다.
        - 내가 검색할 채팅방이 명확하다면 문제없지만, 다른 공고 채팅방이 어떤게 있는지 알고 싶을때는 불편하다. (현재 공고가 뜬 다른 채팅방이 어떤게 있는지 알기 어렵다.)
    2. 채팅목록에 일반 채팅방과 함께 보여지기 때문에 채팅 목록이 어수선해진다.
        - 일반 채팅과 오픈 채팅을 구분하고 싶은 유저에게는 불편한 점이다.
- 해결책
    1. 이 서비스는 개발자 공고에 특화된 서비스이다.
        - 따라서 현재 개설된 채팅방 목록을 한눈에 볼 수 있다.
    2. 필요할 때만 들어와서 확인할 수 있다.
        - 공과사 구분
        - 보다 명확한 목적이 있는 다른 채팅방으로 가기위한 가교 역할
            - 면접 스터디, 코테 준비 스터디에 참여할 사람들을 모으는 창구 역할

2020-06-07 04:02 UTC, sonypark commented on README.md
> +    - 현재 진행중인 개발자 채용/교육 공고 위주 채팅방 생성
네 맞습니다. 이것이 가장 큰 고민인데 카카오 오픈 채팅방과의 차별점은 [여기](https://github.com/woowacourse/woowa-userstory-2020/pull/40#discussion_r436322098) 에 정리를 해보았습니다.

추가로 스터디원을 모집하는 게시판을 만들거나 코테, 면접 후기를 공유하는 게시판을 만드는 것도 좋을 것 같습니다. 😊

2020-06-08 03:46 UTC, toneyparky commented on README.md
> +    - 현재 진행중인 개발자 채용/교육 공고 위주 채팅방 생성
맞아요 소니! 대체제의 장점과 단점을 잘 분석하셨네요.

소니의 서비스는 오픈 채팅방의 단점을 극복할 부분이 보이는걸요!

마냥 오픈 채팅방을 적으로 두기보다는 구현하기 힘든 부분에 대해서는 소니가 언급한 스터디 채팅룸 같이 카톡을 활용하게 하는 방법도 좋은 거 같아요!

2020-06-09 08:42 UTC, gracefulBrown requested changes
안녕하세요 소니! 글 잘 읽었어요 :)
개발자 취업 정보 공유 서비스라니 정말 많은 개발지 취업 준비하시는 분들이 도움을 받을 수 있겠네요 :)

몇가지 의겨을 남겨봅니다.
카카오 오픈 채팅방과의 차별점 부분에서
해결책으로 제시한 이 서비스의 특징이 카카오 오픈채팅방의 단점을 보완할 수 있을지 의문이 듭니다.
또, 단순히 지원자들간의 정보공유로 기존에 정보를 나누고 있던 커뮤니티의 접근성과 정보량을 뛰어넘을 수 있을지에 대한 포인트가 부족해보여요ㅜㅜ

2020-06-11 03:36 UTC, sonypark commented
네 맞습니다.ㅠㅠ 카카오 오픈채팅방이나 기존 커뮤니티와는 정보량과 접근성에서 경쟁을 할 수 없기 때문에, 개발자 취업을 준비하는 사람들에게만 타켓팅한 서비스를 제공하는게 현실적인 차별화 포인트가 될 것 같습니다.

개발자 취업을 준비생이 궁금해할만한 정보에만 집중해서 서비스를 제공해보려고 합니다. (ex. 다른 지원자들과 대화, 다른 사람의 포트폴리오 조회, 면접 후기 조회 등).

2020-06-11 15:55 UTC, gracefulBrown approved these changes
개발자 특화된 정보제공 서비스 괜찮네요. 분명 수요는 있을 것 같군요ㅎㅎ
합격자, 면접 경험자의 경험을 어떻게 이끌어 낼 지, 채팅방에서 정보를 공유하기 위해서는 어떠한 장치를 마련하였는지
와 같은 점들을 함께 고민해봐도 좋을 것 같습니다 ^^
필요성을 느끼고 만드는 서비스는 분명 설득력 면에서 강한 매력을 가질 수 있을 것 같아요!
기대됩니다 :)

2020-06-11 15:55 UTC, merged