[쪼밀리] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #41
Opened 2020-06-04 17:06 UTC by SujinEmilyCho

[여기여기😁🙌](https://github.com/SujinEmilyCho/woowa-userstory-2020/tree/chomily)

2020-06-05 07:04 UTC, icyMojito approved these changes
안녕하세요 쪼밀리~ 쿨라임입니다 😇
여행에서도 개성을 추구하는 요즘 사람들에게 알맞는 서비스를 기획해 주셨네요 👍🏻
몇 가지 피드백을 남겼으니 참조해 주세요!

2020-06-05 07:04 UTC, icyMojito commented on README.md
> +- 원하는 위치의 투어 프로그램을 검색할 수 있다.
개인이 마련한 투어 프로그램만 검색되나요, 아니면 여행사들의 투어 프로그램도 검색되나요?
양쪽 다 검색될 시 필터가 있으면 더 좋을 것 같아요~

더불어 비슷한 서비스인 [마이리얼트립](https://www.myrealtrip.com/)을 참조해 보면 좋을 것 같아 링크 남겨요!
(이미 알고 계셨다면 패쓰 ☺️)

2020-06-05 07:04 UTC, icyMojito commented on README.md
> +- 지도 상에서 투어들을 확인 할 수 있다.
혹시 여러 코스가 포함된 투어면 지도 상에 어떻게 표시가 되나요?
출발지 혹은 도착지에만 표시되는지, 아니면 코스에 포함된 모든 장소에 표시되는지 궁금하네요~

2020-06-05 07:04 UTC, icyMojito commented on README.md
> +- 해당 투어의 페이지에서 투어 예약을 할 수 있다.
이 서비스에 개인이 투어 프로그램을 등록할 때 소정의 가이드 비용이나 예약금을 받고 싶어 한다면,
결제 시스템 도입이 필요할 수 있을 것 같아요!
(서비스의 정책에 따라 계좌이체나 무통장 입금만 가능하게 할 수도 있겠지만요 ㅎㅎ)

2020-06-05 07:04 UTC, icyMojito commented on README.md
> +서울에 사는 김OO 씨는 휴가 동안 경주로 여행을 가기로 했다. 경주에서 유명한 관광지인 첨성대, 안압지 등을 포함하는 코스를 만들어본다. 그러던 중 몇몇 코스는 역사적 배경에 대해서 잘 아는 누군가가 설명을 해주면 더 좋을 것 같다. 그래서 김OO 씨는 동네 사람들에 접속해서 원하는 여행지의 프로그램을 찾아본다. 원하는 투어를 둘러보던 중 2시간짜리 '
시나리오에 '그 동네 사람들'을 이용하여 '여름밤 별빛 역사 걷기' 프로그램을 예약하는 부분이 빠진 것 같네용~

2020-06-05 10:31 UTC, Ramen6315 reviewed
안녕하세요 쪼밀리!

라면입니다.

전체적으로 제공하고자 하는 서비스가 좋은거같아요!
여행 지역을 잘알고 있는 사람을 통해서 행복한 여행을 할 수 있도록 하는게 정말 좋은거같은데요!

제가 남긴 comment는 사용자 이야기에서 생각 해볼만한 단계는 아니라고 생각했지만 이후에 천천히 생각해보셔도 좋을거같아서 comment남겼습니다!

2020-06-05 10:31 UTC, Ramen6315 commented on README.md
> +서울에 사는 김OO 씨는 휴가 동안 경주로 여행을 가기로 했다. 경주에서 유명한 관광지인 첨성대, 안압지 등을 포함하는 코스를 만들어본다. 그러던 중 몇몇 코스는 역사적 배경에 대해서 잘 아는 누군가가 설명을 해주면 더 좋을 것 같다. 그래서 김OO 씨는 동네 사람들에 접속해서 원하는 여행지의 프로그램을 찾아본다. 원하는 투어를 둘러보던 중 2시간짜리 '
이미 고려 하셨을거 같지만 개인의 경우 투어 내용과, 개인 가이드의 신분에 대한 명확한 검증이 필요하다고 생각이 들었어요!
새로운 사람을 만나는 것도 좋지만 투어 내용이나 개인 가이드에 대한 신뢰가 명확하지 않다면 서비스를 이용 하기 어려울거같아요!

사용자 이야기에서 고려할만한 내용은 아니지만 한번쯤 생각해보는것도 좋다고 생각해서 comment남깁니다!

2020-06-05 14:47 UTC, hongbin-dev reviewed
안녕하세요. 쪼밀리! 리뷰어 앨런입니다. ✌✌
혼자 여행을 다닌적이 있었는데, 해당 서비스를 사용하면 더 좋은 기억을 남길 수 있다고 생각되네요!
또 시나리오와 요구사항을 잘 작성해주셔서 읽기 좋았습니다.
몇 가지 궁금한게 있어서 코멘트 남깁니다.

감사합니다. 😀😀

2020-06-05 14:47 UTC, khb1109 commented on README.md
> +- 나만 알기 아까운 지역 정보를 바탕으로 참여자에게 서비스를 제공한다.
이 부분은 아래 투어 제공자의 몫인가요? 
어떤이의 역할인지 약간의 설명이 들어가도 좋을 것 같아요.

2020-06-05 14:47 UTC, khb1109 commented on README.md
> +##### 2~30대 여행자 김OO
쪼금 더 구체화해도 좋을 것 같아요!

2020-06-05 14:47 UTC, khb1109 commented on README.md
> +서울에 사는 김OO 씨는 휴가 동안 경주로 여행을 가기로 했다. 경주에서 유명한 관광지인 첨성대, 안압지 등을 포함하는 코스를 만들어본다. 그러던 중 몇몇 코스는 역사적 배경에 대해서 잘 아는 누군가가 설명을 해주면 더 좋을 것 같다. 그래서 김OO 씨는 동네 사람들에 접속해서 원하는 여행지의 프로그램을 찾아본다. 원하는 투어를 둘러보던 중 2시간짜리 '
저도 라면말의 동감하는 부분입니다. 
이 부분은 아이디어 구체화의 문제라고 생각하여 이 단계에서 생각하는게 맞는지 모르겠지만
서비스 제공자가 믿을 수 있는 가이드를 소개해야할 것 같습니다. 범죄로 이어질 수 있다고 생각이 드네요.

2020-06-05 14:47 UTC, khb1109 commented on README.md
> +- 나만 알기 아까운 지역 정보를 바탕으로 참여자에게 서비스를 제공한다.
`서비스를 제공한다` 라는 말이 추상적이라고 생각돼요!
투어를 이야기하는걸까요?

2020-06-05 14:53 UTC, minuyim approved these changes
안녕하세요 쪼밀리

작성해주신 시나리오 잘 읽어봤습니다. 전체적으로 여행을 할 때 있었으면 좋겠다라는 내용이 들어가 있어서 읽는데 즐거움을 느꼈습니다.

고려해보셨겠지만 이 서비스는 추후에 확장 가능성도 많이 보이는 것 같아요. 현재는 단순히 여행객과 그 지역 가이드를 연결해주는 역할을 했지만 더 나아가 여행 플랫폼으로 발전해 사용자가 직접 만들어 가는 여행상품이 나올 수도 있을 것 같습니다. 그 과정에서 플랫폼은 수수료만 얻으면 되겠네요.

다만 가이드에 대한 신뢰성 확보가 중요한 측면인 것 같습니다. 여행 상품 자체뿐만 아니라 가이드에 대한 충분한 정보도 제시해준다면 만족스러운 여행이 될 것 같습니다. 다만 이 경우에는 유명 가이드만 쫒아가는 현상이 일어날 수도 있어, 지역민의 관광 추천보다는 유명 여행사의 또 다른 유통 창구와 다름없게 될 수도 있을 것 같습니다.

2020-06-05 14:53 UTC, minuyim commented on README.md
> +- 해당 투어의 정원, 비용, 예상 시간 등 상세 정보를 열람할 수 있다.
추가로 가이드에 정보까지 제공해준다면 가이드 매칭 플랫폼으로 더 발전할 여지가 보이는 것 같아요!

2020-06-08 06:09 UTC, SujinEmilyCho commented on README.md
> +- 원하는 위치의 투어 프로그램을 검색할 수 있다.
상업화되고 이미 알려진 투어와는 다르고, 좀 더 로컬한 투어를 제공하는 것이 이 서비스의 컨셉이었어서 개인이 준비한 투어를 우선으로 제공하는 서비스를 생각했어요~ 서비스가 커지면 여행사에서도 투어 등록을 제안받을 수 있을 것 같은데요! 그 경우에는 광고/추천 등의 문구를 붙여서 따로 노출되게 하는 것이 좋겠다고 생각했어요😊 쿨라임이 이야기해준 것처럼 검색할 때 필터로 등록해주면 더 좋을 것 같네요! 👍

혹시 서비스의 컨셉이나 여행사의 투어 프로그램 노출에 대한 다른 생각이나 좋은 아이디어 있으시면 부탁드릴게요!😉

2020-06-08 06:26 UTC, SujinEmilyCho commented on README.md
> +- 지도 상에서 투어들을 확인 할 수 있다.
투어가 포함하는 위치에 모두 핀을 붙여주는 것이 해당 을 모두 표기해주는 것으로 생각했습니다! 그래야 각 지점에 대한 투어를 찾는 사람에게도 노출이 될 것 같아요~ 그러고보니 투어를 등록할 때도 여러 위치를 표기할 수 있도록 지원해야겠군요! 코멘트 고맙습니다😊

2020-06-08 06:26 UTC, SujinEmilyCho commented on README.md
> +- 해당 투어의 페이지에서 투어 예약을 할 수 있다.
결제 시스템 이야기가 빠졌군요! 반영했습니다😊

2020-06-08 06:42 UTC, SujinEmilyCho commented on README.md
> +서울에 사는 김OO 씨는 휴가 동안 경주로 여행을 가기로 했다. 경주에서 유명한 관광지인 첨성대, 안압지 등을 포함하는 코스를 만들어본다. 그러던 중 몇몇 코스는 역사적 배경에 대해서 잘 아는 누군가가 설명을 해주면 더 좋을 것 같다. 그래서 김OO 씨는 동네 사람들에 접속해서 원하는 여행지의 프로그램을 찾아본다. 원하는 투어를 둘러보던 중 2시간짜리 '
맞아요! 이 대해서 문제를 최소화하기 위한 여러 안전 장치들을 생각해보았는데요~

먼저, SNS를 통한 회원가입을 진행할 때 API로부터 이름, 연락처 등의 개인정보를 제공 받고, 휴대폰 인증으로 신분에 대해 어느 정도 인증을 할 수 있을 것입니다.

그리고 가이드는 모바일의 GPS를 통해서 제공하는 투어가 이루어지는 곳에 거주하는 것을 간접적으로 증명합니다.

마지막으로 투어를 제공하는 사람과 투어 참여자 사이의 평가 시스템을 도입해서 서로에 대해 어느 정도 신뢰를 쌓을 수 있을 것이라고 생각합니다!

혹시 추가적으로 좋은 아이디어 있으시면 알려주세요! 의견 고맙게 받겠습니다😊

2020-06-08 06:49 UTC, Ramen6315 approved these changes
쪼밀리

피드백 수정 하느라 고생하셨습니다.
Approve 하겠습니다!

2020-06-08 08:18 UTC, hongbin-dev approved these changes
수고하셨습니다.

2020-06-09 02:28 UTC, pobiconan requested changes
최근 코로나 이슈 때문에 여행 서비스가 많이 힘들어하는 상황인데 여행 서비스에 도전하는군요.
힘든 길인지 앎에도 불구하고 도전하는 정신 💯 
해외여행 안되면 국내여행하면 되고, 올해는 힘들지만 내년에는 좋아지겠죠?

이 서비스 성공의 핵심은 컨텐츠 확보네요. 
현지인들의 참여가 높아 양질의 컨텐츠가 쌓이면 분명 성공할 수 있으리라 생각해요.
그런 측면에서 현지인들의 관점에서 "내가 왜 이 컨텐츠를 제공해야할까?"라는 측면에 대한 페르소나도 작성해 보면 어떨까요?
제공자와 사용자 중 누가 먼저랄 수는 없지만 현지인들의 관점도 상당히 중요할 것 같은데요.

2020-06-09 09:01 UTC, SujinEmilyCho commented
안녕하세요 포비!😊

맞아요~ 요즘 코로나 이슈 때문에 여행업계가 많은 어려움을 겪고 있죠...! 그래도 코로나 백신에 대한 이야기도 나오고, 올해는 힘들어도 내년이라도 조만간 마스크 없는 생활이 올거라 믿어요🙏 또 코로나로 인해 사람들이 여행에 대한 욕구가 많이 쌓여 있을텐데, 코로나가 종식되고 나면 억눌려있던 여행 서비스에 대한 요구가 엄청나게 많아질 것 같아요. 현재 여행 서비스 업계가 타격은 상태라서 진입장벽도 낮고 지금이 오히려 타이밍일지 모르겠단 생각도 들어요! 예전부터 있었으면 좋겠다 싶었던 서비스에서 시작한 것 이기도 하구요😊

피드백 주신 것처럼 다채롭고 퀄리티가 좋은 컨텐츠가 많아지는 것이 이 서비스가 성공하기 위해 중요한 포인트인 것 같아요! 투어를 제공하려는 현지인들은 여러 분류가 있을 것 같은데요! 아래와 같이 정리해보았어요.

- 그 지역의 프리랜서 투어가이드
- 역사, 동네 알리는 것을 좋아하는 사람
- 새로운 사람 만나는 것을 좋아하는 사람
- 부수입을 원하는 사람
- 1일 클래스(ex, 꽃꽂이 공방, 가죽 공예 등) 선생님
- 가이드 혹은 사람들 리딩 경험이 필요한 사람

이번 유저 시나리오에서는 새로운 사람들을 만나는 것을 좋아하면서 부수입이 필요한 사람을 투어 가이드의 페르소나로 풀어보았습니다!

리뷰 감사합니다😁

2020-06-09 09:06 UTC, SujinEmilyCho commented
안녕하세요 포비!😊

맞아요~ 요즘 코로나 이슈 때문에 여행업계가 많은 어려움을 겪고 있죠...! 그래도 코로나 백신에 대한 이야기도 나오고, 올해는 힘들어도 내년이라도 조만간 마스크 없는 생활이 올거라 믿어요🙏 또 코로나로 인해 사람들이 여행에 대한 욕구가 많이 쌓여 있을텐데, 코로나가 종식되고 나면 억눌려있던 여행 서비스에 대한 요구가 엄청나게 많아질 것 같아요. 현재 기존의 여행 사업이 큰 타격을 입은 상태라서 진입장벽도 낮고 지금이 오히려 타이밍일지 모르겠단 생각도 들어요! 예전부터 있었으면 좋겠다 싶었던 서비스에서 시작한 것 이기도 하구요😊

포비 말씀처럼 다채롭고 퀄리티가 좋은 컨텐츠가 많아지는 것이 이 서비스가 성공하기 위해 중요한 포인트인 것 같아요! 투어를 제공하려는 현지인들은 여러 분류가 있을 것 같은데요! 아래와 같이 정리해보았어요.

그 지역의 프리랜서 투어가이드
역사, 동네 알리는 것을 좋아하는 사람
새로운 사람 만나는 것을 좋아하는 사람
부수입을 원하는 사람
1일 클래스(ex, 꽃꽂이 공방, 가죽 공예 등) 선생님
가이드 혹은 사람들 리딩 경험이 필요한 사람
이번 유저 시나리오에서는 새로운 사람들을 만나는 것을 좋아하면서 부수입이 필요한 사람을 투어 가이드의 페르소나로 풀어보았습니다!

리뷰 감사합니다😁

2020-06-09 23:05 UTC, pobiconan approved these changes
지금과 같이 여행산업이 어려울 때 시작하는 것이 기회가 될 수 있다는 말이 공감이 되네요. 💯 
충분히 수요가 있는 서비스라 생각하니 최종 후보에 선정되어 빛을 볼 수 있기를...

2020-06-09 23:05 UTC, merged