[둔덩] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #45
Opened 2020-06-04 17:27 UTC by DunDung

[잘 부탁드립니다!](https://github.com/DunDung/woowa-userstory-2020/blob/story/README.md)

2020-06-05 02:19 UTC, LTTTTTE approved these changes
직장인들의 고충들을 잘 모아서 하나의 서비스로 잘 계획하신것 같습니다.
추가적인 서비스들도 기본 기능구현 이후 점차 구현된다면 더욱더 좋은 사이트가 되겠네요.
애매해 보이는 부분 코멘트 남겨드렸습니다. 확인부탁드려요.

2020-06-05 02:19 UTC, LTTTTTE commented on README.md
> +|회사에서도 게임이 하고 싶다. 누군가와 경쟁하며 나의 게임 실력을 뽐내고 싶다. 하지만 회사에서는 맘 놓고 게임에 집중할 수 없다.|상사의 눈을 피해 누군가와 경쟁하는 게임을 할 수 있다.|
외부 게임을 남 눈치 못채게 할수 있게 하는 서비스 인가요?
아님 사이트 내에서 몰래 하기 편한 게임을 제공하는 건가요?

2020-06-05 07:12 UTC, DunDung commented on README.md
> +|회사에서도 게임이 하고 싶다. 누군가와 경쟁하며 나의 게임 실력을 뽐내고 싶다. 하지만 회사에서는 맘 놓고 게임에 집중할 수 없다.|상사의 눈을 피해 누군가와 경쟁하는 게임을 할 수 있다.|
애매하게 작성한 부분이 있네요!
서비스 자체를 몰래할 수 있게 디자인을 구성하고, 서비스 안에서 게임을 제공하자는 의도였어요.
수정했습니다 : )

2020-06-05 07:49 UTC, pci2676 approved these changes
둔덩 재밌게 잘봤습니다!
B 어플이 생각나는데요! 서비스만의 시그니쳐 기능이 중요하겠네요!

2020-06-05 07:49 UTC, pci2676 commented on README.md
> +|아침부터 분주하다. 입고 싶은 스타일은 많은데 이렇게 입으면 추울 것 같고, 저렇게 입으면 더울 것 같고.. 날씨를 검색하고 옷장을 들여다보고를 반복한다.|날씨와 체감 온도에 맞는 옷 종류와 스타일을 추천해줄 수 있다.|
커뮤니티니까 사용자끼리 서로 추천을 해주는건가요??
날씨가 지역마다 다를수도 있어서 그러한 점도 고려할수 있어야 할 것 같아요!

2020-06-05 08:39 UTC, DunDung commented on README.md
> +|아침부터 분주하다. 입고 싶은 스타일은 많은데 이렇게 입으면 추울 것 같고, 저렇게 입으면 더울 것 같고.. 날씨를 검색하고 옷장을 들여다보고를 반복한다.|날씨와 체감 온도에 맞는 옷 종류와 스타일을 추천해줄 수 있다.|
저는 서비스에서 추천해주는 걸  기능으로 생각했는데
사용자끼리 추천해주는 것도 좋은 것 같아요!!

2020-06-05 11:41 UTC, jjj0611 approved these changes
기획 잘 봤어요 둔덩 :)
무료한 일상에서 좀 더 재미를 찾고 싶어하는 직장인을 잘 공략한 기획인 것 같아요!
다만 기존에 있는 유사 서비스와 어떻게 차별점을 가져갈건지가 매우 중요해보입니다!
시장에 이미 존재하는 서비스를 이기려면 차별화된 무기나 세분화된 타겟팅이 필요해보여요!
잘 구현해서 저희도 나중에 자주 사용하는 커뮤니티가 되면 좋겠네요!

2020-06-05 11:41 UTC, jjj0611 commented on README.md
> +## 직장인을 위한 기능들을 모아놓은 직장인 커뮤니티
기능들을 모아놓은 직장인 커뮤니티에서 기능들이라는 것이 좀더 세분화 되어 있으면 좋을 것 같아요.
지금 적은 것으로는 음식 추천, 집단 게임, 날씨에 따른 옷 추천, 익명 커뮤니티 공간 정도로 보이는데
집단 게임은 게임의 컨텐츠 자체가 중요할 것 같고,
커뮤니티 공간은 기존에 B****앱과 비슷할 것 같아요!
기존에 존재하던 커뮤니티를 이기기 위해서는 좀 더 세분화된 타겟팅이나 차별화된 기능이 있으면 좋을 것 같아요 :)

2020-06-05 11:41 UTC, jjj0611 commented on README.md
> +> 박월루는 회사에서 대부분 한가하고 심심하다. 하지만 뒤에 있는 상사의 자리에서 내 자리가 보이기 때문에 딴짓을 하기엔 눈치가 보인다. 퇴근 시간은 멀었는데 심심해 죽겠다. 그래서 직장인탐구생활(가제)에 접속했다. 이 사이트는 딴 짓을 하는 게 티가 안나기 때문에 몰래 놀기에 좋다. 사용자들끼리 점수를 경쟁할 수 있는 간단한 게임을하며 오늘도 퇴근시간을
게임 자체의 컨텐츠가 매우 중요할 것 같아요!
간단한 게임인데 사용자들이 재밌게 할 수 있는 게임이어야 할 것 같아요

2020-06-05 11:41 UTC, jjj0611 commented on README.md
> +|날씨에 맞는 입을 옷 종류를 추천받고 나만의 스타일로 코디해서 출근했다.|날씨와 체감 온도에 맞는 옷 종류와 스타일을 추천해줄 수 있다.|
많은 사람들이 고민하는 문제일 것 같아요.
잘 개발할 수 있다면 매우 유용하게 쓰이겠네요 :)

2020-06-06 06:01 UTC, hotheadfactory approved these changes
안녕하세요 둔덩:)
진짜 직장인 필수 서비스가 될 듯한 좋은 아이디어네요.
다만 기존에 유사한 서비스들이 있는 만큼 실제 제작에 들어간다면 이 글에서 설명된 차별점을 부각시키도록 노력할 필요가 있어 보여요.

2020-06-06 06:01 UTC, hotheadfactory commented on README.md
> +> 박월루는 회사에서 대부분 한가하고 심심하다. 하지만 뒤에 있는 상사의 자리에서 내 자리가 보이기 때문에 딴짓을 하기엔 눈치가 보인다. 퇴근 시간은 멀었는데 심심해 죽겠다. 그래서 직장인탐구생활(가제)에 접속했다. 이 사이트는 딴 짓을 하는 게 티가 안나기 때문에 몰래 놀기에 좋다. 사용자들끼리 점수를 경쟁할 수 있는 간단한 게임을하며 오늘도 퇴근시간을
재미있네요 :) 이런 부분에서 확실히 블X인드와 차별화가 되겠네요!

2020-06-06 06:01 UTC, hotheadfactory commented on README.md
> +> 김결정은 오늘도 회사에 출근한다. 김결정의 유일한 낙은 혼자 맛있는 음식을 먹는 것이다. 어제는 먹고 싶은 음식이 참 많은 날이였다. 결정을 잘 못하는 성격때문에 항상 오랜 시간 메뉴 선택에 허비하고 결정을 후회했었는데, 처음으로 직장인탐구생활(가제)에 접속하여 메뉴 결정 기능을 사용했다. 심리에 기반한 간단한 몇가지 질문에 대답하니 내가 진짜 먹고싶
나중에 추가 목표로 잠실이면 잠실, 판교면 판교 등 권역별로 맛집 추천 리스트를 사용자 투고로 받고 랜덤 추천하게 해도 재밌을 것 같아요!

2020-06-07 18:55 UTC, DunDung commented on README.md
> +## 직장인을 위한 기능들을 모아놓은 직장인 커뮤니티
맞는 말씀입니다!
차별화되고 참신한 기능을 더 생각해보겠습니다...!

2020-06-07 18:56 UTC, DunDung commented on README.md
> +> 박월루는 회사에서 대부분 한가하고 심심하다. 하지만 뒤에 있는 상사의 자리에서 내 자리가 보이기 때문에 딴짓을 하기엔 눈치가 보인다. 퇴근 시간은 멀었는데 심심해 죽겠다. 그래서 직장인탐구생활(가제)에 접속했다. 이 사이트는 딴 짓을 하는 게 티가 안나기 때문에 몰래 놀기에 좋다. 사용자들끼리 점수를 경쟁할 수 있는 간단한 게임을하며 오늘도 퇴근시간을
점수 경쟁을 통해 재미를 만들 수 있는 간단한 게임을 게임을 생각하고 있습니다!

2020-06-07 18:57 UTC, DunDung commented on README.md
> +> 김결정은 오늘도 회사에 출근한다. 김결정의 유일한 낙은 혼자 맛있는 음식을 먹는 것이다. 어제는 먹고 싶은 음식이 참 많은 날이였다. 결정을 잘 못하는 성격때문에 항상 오랜 시간 메뉴 선택에 허비하고 결정을 후회했었는데, 처음으로 직장인탐구생활(가제)에 접속하여 메뉴 결정 기능을 사용했다. 심리에 기반한 간단한 몇가지 질문에 대답하니 내가 진짜 먹고싶
재밌는 아이디어가 될 것 같네요!! 감사합니다 히로 : )

2020-06-09 01:43 UTC, pobiconan requested changes
근무 중에는 일만해야하는 것 아닌가요? ㅋㅋㅋ
근무 중 짬짬히 무엇인가 재미난 놀꺼리를 만들어 준다는 의도는 좋네요. 💯 

단, 너무 다양한 기능을 제공하려는 욕심이 보이고, 직장인으로서 각 기능이 그렇게 매력적으로 느껴지지는 않아 아쉬움이 있네요.
무엇인가 기존 서비스들과는 차별점을 가지면서 직장인들의 관심을 가질 수 있는 엣지랄까 뭐 그런 것이 보이지 않는 것 같아요. 직장인이들이 이 서비스를 쓰고 싶다라는 마음이 들 수 있는 그런 찐한 기능 없을까요?
주변 직장 선배들에게 한번 물어보는 것은 어떨까요?

2020-06-10 11:15 UTC, DunDung commented
서비스 설명을 직장인들 노는 것에만 집중해서 써놨었네요..ㅠㅠㅠㅠ
놀거리도 물론 제공되지만 저의 의도는 직장인들이 필요한 기능을 모아놓는 것이였습니다!!

다양한 기능을 제공하려던 욕심을 버리고 주변 직장인 선배들과 지인의 지인들을 조사해서,
정부, 지자체, 기업 등에서 자신이 받을 수 있는 혜택을 조회할 수 있는 기능을 생각해봤습니다...,

그래서 제가 생각한 차별화된 기능은 세가지입니다..!

1. 심리 기반 간단한 질문을 통한 음식 추천 
2. 사이트를 일하는 것처럼 보여주는 디자인과 속한 집단, 단체 내 경쟁을 유발할 수 있는 간단한 게임
3. 자신이 받을 수 있는 혜택 조회

직장인들의 관심을 끌기에는 부족할까요..ㅠㅠ

2020-06-10 23:38 UTC, pobiconan approved these changes
직장 생활을 하면 지칠 때 위로 받고, 눈치보지 않고 뭔가를 할 수 있는 그런 서비스가 되면 좋겠네요. 💯 
제가 사용할 일이 많지는 않겠지만 저도 사용할 수 있는 그런 서비스로 만들어 주세요.
꼭 10개 후보에 선정될 수 있기를

2020-06-10 23:38 UTC, merged