[카일] 사용자 스토리 제출합니다.
woowacourse/woowa-userstory-2020 pull request #5
Opened 2020-06-04 06:07 UTC by KIMSIYOUNG

[여기](https://github.com/KIMSIYOUNG/woowa-userstory-2020/tree/docs/kyle)를 확인하세요. !

2020-06-04 14:14 UTC, hwanghe159 approved these changes
안녕하세요 카일~! 잘읽었어요
이 서비스는 특히 자취하는 사람들, 택배를 기다릴 시간이 없는 사람들, 그리고 택배비가 아까운 사람들한테 특히 유용할 것 같아요.
제가 자취를 하고 있을때 이런 서비스가 있었다면 바로 사용했었을 것 같네요!

2020-06-04 14:14 UTC, hwanghe159 commented on README.md
> +라빈은 자취를 시작하고 물건을 최저가로 구매하게 되었다. 온라인을 이용할 땐 최저가를 비교하여 쉽게 구매하였지만, 오프라인에서는 최저가 비교가 힘들었다. 상대적으로 마트가 편의점보단 싼데 어느 마트가 더 싼지는 알 수가 없다. 친구의 추천으로
오프라인 마트의 가격 데이터를 어떻게 받아올 것인지, 수시로 변경되는 가격에 대해서는 어떻게 업데이트 할 것인지 생각해 보니까 마트 사장님들도 이 서비스의 고객이 되어야 하겠다는 생각을 했어요. 마트 사장님들이 이 서비스를 이용함으로써 어떤 가치를 얻게 되는지 고민해보면 좋을것 같아요!

2020-06-05 02:23 UTC, yelimkim98 approved these changes
안녕하세요 카일! 저도 음식 살때 이 가게 저 가게 왔다갔다하면서 어떻게든 싼걸 사려고 하는데, 이 서비스가 존재한다면 저는 바로 사용했을것 같아요!
이 서비스는 초반에 (최저가 캐치에 대한)정확성을 마련하는게 관건일 것 같네요!

2020-06-05 02:23 UTC, yelimkim98 commented on README.md
> +- 온/오프라인 최저가 서비스를 이용하는 고객은 일반적으로 식료품이나 생활용품을 제외한 대부분의 상품을 온라인으로 구매합니다. 따라서 생활용품과 식료품을 위주로 하는 최저가 서비스를 제공할 예정입니다.
오프라인 최저가를 얼마나 잘 캐치해내느냐가 관건이겠네요!
동네 마트, 편의점, 나들가게 등 자세하게 커버하면 커버할수록 소비자에게 유용하게 느껴질 것 같네요!

2020-06-05 02:23 UTC, yelimkim98 commented on README.md
> +앱을 설치했다. 물을 구매하고 싶어 현 위치를 기반으로 검색했더니 근처에서 물을 구매할 수 있는 곳의 리스트가 나온다. 리스트 중 가장 저렴한 가격을 기준으로 정렬되어 있어 바로 가서 구매하였다. 시원하게 물을 마시고 집에 가는 길에 로션이 떨어진 것이 생각이나, 앱을 키고 최저가로 로션을 구매한 후 집으로 간다.
가로스크롤 불편합니다!!!!

2020-06-05 02:25 UTC, hyochan-Kim approved these changes
카일 재밌게 읽었습니다!
보통 마트에 갔을 때 하나의 물품만 구매하는 것은 아닐 것 같아요.
그런데 온라인과 다르게 오프라인은 여러 곳에서 구매를 하기가 쉽지 않죠!
이런 관점에서 물품의 최저가가 아니라, 장바구니에 물건들을 담고 그 물건들의 총액이 최저가인 마트를 추천하는 기능이 추가되면 좋을 것 같습니다.
고생하셨어요!! 👍

2020-06-05 02:25 UTC, hyochan-Kim commented on README.md
> +앱을 설치했다. 물을 구매하고 싶어 현 위치를 기반으로 검색했더니 근처에서 물을 구매할 수 있는 곳의 리스트가 나온다. 리스트 중 가장 저렴한 가격을 기준으로 정렬되어 있어 바로 가서 구매하였다. 시원하게 물을 마시고 집에 가는 길에 로션이 떨어진 것이 생각이나, 앱을 키고 최저가로 로션을 구매한 후 집으로 간다.
로션처럼 보통 구비해 두지 않는 생필품에 대해 제공된다면 훨씬 사용 빈도가 높을 것 같습니다. 👍 👍

2020-06-05 02:25 UTC, hyochan-Kim commented on README.md
> +라빈은 자취를 시작하고 물건을 최저가로 구매하게 되었다. 온라인을 이용할 땐 최저가를 비교하여 쉽게 구매하였지만, 오프라인에서는 최저가 비교가 힘들었다. 상대적으로 마트가 편의점보단 싼데 어느 마트가 더 싼지는 알 수가 없다. 친구의 추천으로
정말 번화가가 아니라면 주변에 마트가 여러 곳인 상황이 흔하지 않을 것 같아요! 최저가 비교 대상이 많을지 우려가 되네요~

2020-06-05 02:25 UTC, hyochan-Kim commented on README.md
> +    - 자취
한번에 물건을 많이 사지 않는 자취생에게는 온라인의 배송료나 최저 금액이 부담스러운 경우가 많죠! 자취생들은 필요성을 공감할 것 같습니다 👍

2020-06-06 00:07 UTC, moonyoungCHAE approved these changes
카일! 잘 읽었어요. 재미있는 아이디어네요.
특히 자취생에게 유용한 서비스가 될 것 같아요. 👍

2020-06-06 00:07 UTC, moonyoungCHAE commented on README.md
> +- 온/오프라인 최저가 서비스를 이용하는 고객은 일반적으로 식료품이나 생활용품을 제외한 대부분의 상품을 온라인으로 구매합니다. 따라서 생활용품과 식료품을 위주로 하는 최저가 서비스를 제공할 예정입니다.
히히의 말처럼 오프라인 최저가를 잘 파악하는 게 중요한 이슈겠네요.
어떤 식으로 오프라인 최저가를 파악할지 궁금합니다.
가게 주인의 등록인지, 사용자의 제보인지 궁금해요~

2020-06-06 00:07 UTC, moonyoungCHAE commented on README.md
> +    - 물건을 싸게 사고 싶다.
오프라인의 범위를 정하면 좋을 것 같아요!
처음 만들 때 서울 전체만 해도 큰 범위이기 때문에 잠실 지역으로 규모를 줄이면 어떨까요?

2020-06-06 10:01 UTC, YerinCho reviewed
저처럼 돈 없는 자취생에게 정말 필요하네요 ㅠㅅㅠ
행사로 인해 물품을 사는 수량에 따라 바뀌는 가격(2+1 등) 등등 다양한 케이스의 상품 데이터를 커버할 수 있어야 할 것 같다는 생각이 들었어요!
바뀌는 정보에 대해서 빠른 반영이 가장 중요한 이슈가 될 것 같아요.
마트의 가격 정보가 바뀌었는데 반영되어있지 않아서 헛걸음하게 된다면 소비자의 만족도가 떨어지게 될 테니까요!

2020-06-06 10:01 UTC, YerinCho commented on README.md
> +|물과 같은 식료품이 아닌 생활용품에서도 사용을 원한다.| 화장품과 같은 생활용품의 카테고리와 상품도 추가한다.|
생활용품이라는 카테고리의 범위가 어느정도일지 생각해 볼 필요도 있을 것 같아요!

2020-06-06 10:01 UTC, YerinCho commented on README.md
> +라빈은 자취를 시작하고 물건을 최저가로 구매하게 되었다. 온라인을 이용할 땐 최저가를 비교하여 쉽게 구매하였지만, 오프라인에서는 최저가 비교가 힘들었다. 상대적으로 마트가 편의점보단 싼데 어느 마트가 더 싼지는 알 수가 없다. 친구의 추천으로
사용자를 소비자와 판매자 모두로 정한다면, 사장님들 입장에서는 이 서비스를 통해 마트 홍보효과 등을 기대할 수 있지 않을까요? 그런 점을 부각하면 데이터를 받아오는 데 도움이 될 것 같아요! 사용자의 범위가 넓어지면 사장님 입장의 시나리오도 있으면 좋겠네요!

2020-06-07 15:41 UTC, YerinCho approved these changes

2020-06-08 12:11 UTC, wmakerjun requested changes
안녕하세요 준이에요 🕺
자취생들에게 굉장히 의미있는 아이디어를 기획해준 것 같아요!
이 아이디어를 더 빛나게 해주려면 오프라인으로 비교를 가장 많이 할만한 품목들을 추리는게 중요할 것 같아요!!! 그래야 처음에 사람들에게 서비스 소개할 때도 더 설득력있고 써보고 싶다라는 생각이 들 것 같아요. 👍

2020-06-08 12:11 UTC, wmakerjun commented on README.md
> +## 서비스에 필요한 데이
데이'터'인거죠? ㅎㅎ

2020-06-08 12:11 UTC, wmakerjun commented on README.md
> +모 가게를 운영하는 최사장님은 최근 마트보다 편의점을 찾는 젊은이들이 많아 걱정이다.
마트에서 취급하는 품목의 종류가 굉장히 많을 것 같은데요 주로 어떤 아이템을 위주로 시작할건지 고민해보는것도 중요할 것 같아요~ 
마트 사장님이 처음부터 모든 품목을 올리기는 쉽지 않을 것 같아요 😭 
제 생각에 보통 마트가 편의점보다 저렴하기 때문에 상대적으로 가격변동이 큰 과일같은게 업로드 되는게 좋을 것 같아요!

2020-06-08 12:11 UTC, eastjun commented on README.md
> +디디는 로션을 최저가로 구매하고자 한다. 하지만 현재 위치 근처에서 바로 구매하기를 원한다. 앱을 켜서 확인해본 결과 가장 가까운 곳에 올리브영이 있었고,
위에서
서비스 초기에는 잠실 지역에 한정해서 운영하고 취급하는 물품은 편의점에서 제공하는 물품으로 제한한다.(빵, 튀김과 같은 특수 물품 제외)  
라고 했는데

디디의 예시같은 경우는 나중에 확장됐을 때를 의미하는거죠~? 👀

2020-06-09 05:06 UTC, KIMSIYOUNG commented on README.md
> +## 서비스에 필요한 데이
네! 수정하였습니다.

2020-06-09 05:07 UTC, KIMSIYOUNG commented on README.md
> +디디는 로션을 최저가로 구매하고자 한다. 하지만 현재 위치 근처에서 바로 구매하기를 원한다. 앱을 켜서 확인해본 결과 가장 가까운 곳에 올리브영이 있었고,
네! 맞습니다. 상품의 가격 데이터를 얻는 부분이 어려울 것 같아서, 초기에는 데이터를 받을 수 있는 상품부터 시작하려고 합니다.

2020-06-09 05:12 UTC, KIMSIYOUNG commented on README.md
> +모 가게를 운영하는 최사장님은 최근 마트보다 편의점을 찾는 젊은이들이 많아 걱정이다.
네! 우선적으로 시행할 품목들에 대해서 추가로 기술하였습니다.

2020-06-09 08:34 UTC, wmakerjun approved these changes

2020-06-09 08:34 UTC, eastjun commented
당장 크루들에게 필요할 수 있는 서비스 고민하고 발전시키느라 너무 고생했습니다 👍
더욱 빛나는 아이디어와 서비스가 되길 바라며 merge할게요 😄

2020-06-09 08:35 UTC, merged