[보스독] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #53
Opened 2020-06-06 05:59 UTC by yeonnseok

리뷰어님들! 안녕하세요.
기획 아이디어를 변경하게 되어서 다시 한번 풀리퀘를 보내드립니다.😅
다들 주말 잘보내시고 잘 부탁드립니다!

2020-06-06 08:06 UTC, begaonnuri approved these changes
안녕하세요 보스독 🐕
이번 미션때문이 아니라 평소에 생각해두신 주제같아요.
본인이 어느정도 서비스에 대한 답을 많이 정해놓은것 같은 인상을 받았어요. 기대됩니다!
코멘트 남긴 부분은 명확히 하고 가면 좋을것 같아요!
이만, Approve 하겠습니다 💯 

리뷰와 별개로, 이 서비스가 메이저 서비스가 된다면 결과적으로 면접의 난이도는 점점 더 올라갈 것같아요.
모범답안이 평범한 답안이 되어버릴테고, 인사 담당자들도 해당 서비스를 보고 질문을 변형할테니까요 😭

2020-06-06 08:06 UTC, begaonnuri commented on README.md
> +면접 "질문"과 "답변"을 집단 지성을 통해 쌓아가며 공유하는 서비스
좋은 아이디어라고 생각해요!

[코멘토](https://comento.kr/)라는 유사한 서비스가 있지만 '같은 취준생들이 작성한다는 점'과 같이 보스독 서비스만의 차이점을 명확히 정하고 시작하면 좋을것 같아요.

2020-06-06 08:06 UTC, begaonnuri commented on README.md
> +  - 태그는 일반 기업 질문 부터 전공 질문 특히 개발자들의 실무 면접 분야까지 폭넓게 존재합니다.(특히 개발자 실무지식 답변은 공부하는데 많은 도움이 될 것이라 생각합니다.)
이 서비스의 핵심은 '양질의 데이터'라고 생각해요.
처음부터 태그를 통해 범위를 제안하지 않고 열어두면 데이터들은 얕고 넓어질것 같아요.
차라리 보스독이 카테고리를 통해 직군의 범위를 미리 제안하고, 점차점차 규모가 커질수록 다양한 직군으로 카테고리를 열어주는게 경쟁력 있을것같아요.

[생활코딩의 영상](https://opentutorials.org/course/1688/9331)에서도 `Start Small`이란 말이 나오네요 😉
물론 영상에선 개발할 때 사이드이팩트 때문에 그런것같지만, 보스독도 Start Small 하는 것이 좋을것같아요

2020-06-06 08:06 UTC, begaonnuri commented on README.md
> +질문 링크를 외부로 공유할 수도 있었지만 내부적으로 마이페이지에 보관할 수 있는 기능도 있었던 것이었다!
평소에 일본 만화를 자주 보시나봐요😂

2020-06-06 08:08 UTC, include42 approved these changes
안녕하세요 보스독, 카프카입니다.
써주신 기획 정말 재미있게 읽었습니다.

정말 실용적인 아이디어이고, 사용자들이 써야 될 이유가 분명해서
읽으며 쭉 공감할 수 있었어요. (당장 나오면 저부터 쓰고 싶네요 ㅎㅎ)
그래서 기획 자체에 대해 지적하기보단, 질문 위주로 리뷰를 남기게 된 것 같네요.

좋은 기획 준비하시느라 고생 많으셨어요.
프로젝트가 잘 진행되어서, 저도 한번 써볼 수 있기를 바라고 있습니다.
미션은 Approve하겠습니다!! 💯

2020-06-06 08:08 UTC, include42 commented on README.md
> +우리 사회에는 다른 지식적인 부분은 인터넷이나, 서적을 통해 정보를 습득하기가 비교적 수월하지만, 면접 공부나 준비를 원활하게 할 수 있는 서비스는 아직 존재하지 않습니다. 커뮤니티를 통해 면접 스터디를 구하거나, 인터넷에서 떠돌아다니는 면접질문을 겨우 찾아서 혼자 답변을 생각해보는 정도에 그칩니다.
제 주변에서도 면접 준비를 어려워하는 사람들이 많더라고요. 스터디를 통해 각자 예상 질문을 준비해 오거나, 아니면 구글링을 통해 합격자들의 정보를 알음알음 모으거나...
이 서비스의 필요성에 다시 한 번 공감하게 되네요. 
만약 서비스가 있다면 저도 사용하고 싶다는 생각이 듭니다. 👍

2020-06-06 08:08 UTC, include42 commented on README.md
> +이 서비스의 핵심기능은 기업정보(면접 질문 출처)를 공개하지 않고, 누군가 보편적인 면접 질문을 올린다면, 다른 유저들이 해당 질문에 대해 자신이 생각한 모범 답안을 댓글로 작성합니다. 좋아요를 많이 받은 답안(댓글)순으로 답안(댓글)이 정렬되는 것이 기본적으로 제공되는 기능입니다.
서비스를 사용해야 할 목적도 분명하고, 서비스 내 활동(좋아요)에 대한 동기도 뚜렷하게 보이네요.

궁금한 점!! 혹시 질문들 자체는 어떻게 정렬되나요? 예를 들어 제일 많은 답안이 올라온 질문부터 보여준다던가...
검색 외에 단순히 쭉 내려서 읽는 사람들이 어떤 순으로 질문들을 접할지 궁금해졌습니다.

2020-06-06 08:08 UTC, include42 commented on README.md
> +- 면접을 무사히 마치고 취업에 성공한 사람들의 면접 지식은 대부분 그날로 소멸되는 것을 막을 수 도 있다점에서도 의미가 있다고 생각합니다.
혹시 취업에 성공한 사람들의 질문에 별도로 합격 딱지를 붙인다던가, 이외의 방벙으로 표시할 계획이 있으신가요?
취업에 성공한 사람들에 대해 말씀해 주셨는데,
서비스를 사용하는 사람들에게는 매력적으로 다가올 것 같아서요.

다만 회사마다 질문을 공개하지 않도록 요청하기도 하고(그게 아니어도 회사 입장에서는 껄끄럽겠지요, 답안이 돌아다니는 것이), 
합격자가 정말 합격했는지 인증하는 것도 어려운 일이니(사내메일 인증 정도..?) 현실성의 문제는 있지만...

그래도 합격자의 후기나 질문은 정말 귀한 레퍼런스일 듯해서, 이 아이디어를 더 살리실 생각이 있는지 궁금했습니다 👍

2020-06-06 08:08 UTC, include42 commented on README.md
> +- 면접을 무사히 마치고 취업에 성공한 사람들의 면접 지식은 대부분 그날로 소멸되는 것을 막을 수 도 있다점에서도 의미가 있다고 생각합니다.
한가지 걸리는 점은, 사이트의 방향성인데요.
저는 "취준생들이 서로 예상질문을 공유해보면서 모범답안을 함께 모아보는 서비스"가 지금의 취지라고 생각합니다.
다만 여기에 "특정 기업에서 출제된 질문"이 올라오는 식으로 서비스가 일종의 족보 모음이 되거나,
혹은 합격자들의 면접 후기 모음 사이트가 된다면 여러 위험성이 있다고 생각해요.
보통 회사들이 면접 질문의 공개에 예민하기도 하고, 사이트의 목적이 흐려지는 면도 있다고 생각해서요.

제 생각에는 그래서 질문 업로드에 제약사항을 달아서,
회사명이나 실제 출제 여부나...이런 디테일 없이 깔끔하게 질문만 업로드가 된다면 어떨까 싶어요.
그러면 필요없는 논란이 생기지는 않을테니까요.

제 개인적인 생각입니다만 글이 많이 길어졌네요.
이에 대해서 한번쯤 고민해보시면 재미있을 듯해서, 의견 남겨보았어요 😂

2020-06-06 10:08 UTC, yeonnseok commented on README.md
> +면접 "질문"과 "답변"을 집단 지성을 통해 쌓아가며 공유하는 서비스
감사합니다!
저도 코멘토를 사용해보긴 했는데 별로덕을 많이 못본것 같네요 ㅠ
코멘토랑 차별성을 갖는 서비스로 발전시켜볼게요!

2020-06-06 10:10 UTC, yeonnseok commented on README.md
> +질문 링크를 외부로 공유할 수도 있었지만 내부적으로 마이페이지에 보관할 수 있는 기능도 있었던 것이었다!
ㅎㅎㅎ 일본만화를 보진않는데..
조금 덕스럽나요?😅

2020-06-06 10:12 UTC, yeonnseok commented on README.md
> +  - 태그는 일반 기업 질문 부터 전공 질문 특히 개발자들의 실무 면접 분야까지 폭넓게 존재합니다.(특히 개발자 실무지식 답변은 공부하는데 많은 도움이 될 것이라 생각합니다.)
동의합니다!
태그도 분명 좋은 기능이지만
처음에는 개발자 면접 질문과 같이 스콮을 좁게 시작하는 것도 좋을 것 같네요! :)

2020-06-06 10:15 UTC, yeonnseok commented on README.md
> +우리 사회에는 다른 지식적인 부분은 인터넷이나, 서적을 통해 정보를 습득하기가 비교적 수월하지만, 면접 공부나 준비를 원활하게 할 수 있는 서비스는 아직 존재하지 않습니다. 커뮤니티를 통해 면접 스터디를 구하거나, 인터넷에서 떠돌아다니는 면접질문을 겨우 찾아서 혼자 답변을 생각해보는 정도에 그칩니다.
제가 인식한 문제에 함께 공감해주시니 감사드리네요 😁 
이 서비스로 인해 취준생들의 고민과 부담이 조금이나 덜어졌으면 좋겠네요 ㅎㅎ

2020-06-06 10:21 UTC, yeonnseok commented on README.md
> +이 서비스의 핵심기능은 기업정보(면접 질문 출처)를 공개하지 않고, 누군가 보편적인 면접 질문을 올린다면, 다른 유저들이 해당 질문에 대해 자신이 생각한 모범 답안을 댓글로 작성합니다. 좋아요를 많이 받은 답안(댓글)순으로 답안(댓글)이 정렬되는 것이 기본적으로 제공되는 기능입니다.
사실 어제 급하게 아이디어를 생각해내느라 index 페이지에서 질문들의 정렬까지는 생각해두지 않았습니다.😭
UX적인 부분이라고 생각해서 아이디어가 채택된다면 추후 팀원들과 결정해도 될 문제라고 생각하는 데요 :)

개인적으로는 만약 회원가입할 때 본인의 관심사(관심 직종)를 태그로 체크해둔다면, 해당 태그가 붙은 게시물들을 우선적으로 정렬해서 최신순으로 화면에 띄워 주는게 어떨까 싶네요 ㅎㅎ

혹시 카프카가 더 좋은 의견을 공유해주신다면 참고하도록 할게요!! :)

2020-06-06 10:32 UTC, yeonnseok commented on README.md
> +- 면접을 무사히 마치고 취업에 성공한 사람들의 면접 지식은 대부분 그날로 소멸되는 것을 막을 수 도 있다점에서도 의미가 있다고 생각합니다.
저도 카프카의 물음이 정말 공감이됩니다. 저 또한 처음 아이디어를 구상했을 때, 기업에서 질문공개를 꺼려한다면, 또한 실제 면접을 본 사람들이 질문 공개에 대해 적극적으로 참여를 안할 수도 있다는 점을 염려하고있었습니다.

그래도 제 생각에 저는 특정 기업이라는 출처를 언급하지 않고, 최대한 태그들로 카테고리를 좁힌 뒤에 면접에 나올법한, 면접에 나온적이 있는 문제들을 구별해서 공유해보는 것만으로도 유의미한 서비스가 될 수 있다고 생각해요.

예를 들어 질문작성자가 질문을 올릴때, "면접에 나온적이 있어요!!", "면접에 나올 수 있을 것같아요!!" 와 같은 문구를 옵션으로 선택할 수 있게 한다면, 면접을 준비하는 사람 입장에서는 굳이 실제로 어느 기업에서 나온 문제인지 알지 않아도

- 실제 면접에 나온적 이 있는지 여부
- 본인이 관심있는 기업 분류 (IT기업, 제조기업, 반도체기업 등)
- 구체적인 태그(백엔드 분야, 프론트 엔드 분야, 파운드리, 통신분야, 공정분야)
 
이정도 분류만 가지고도 충분히 본인이 원하는 기업, 분야, 직무를 통틀어서 공부하는데 도움을 받을 수 있을 것이라고 생각하고 있습니다!ㅎㅎ

그래서 아직까지는 합격 여부를 확인하는 것도 서비스에서 중요한 기능이라고 생각은 하지 않고있어요! 
궁금하신 부분에 조금이나마 답변이 되었는지 모르겠네요 ㅎ
혹시 이와 관련해서 추가적으로 조언해주실 부분있거나 궁금증이 더 남아있으시다면 언제든지 피드백 덧붙여주시면 감사드릴게요! ㅎㅎ

2020-06-07 15:27 UTC, kimevanjunseok approved these changes
안녕하세요 보스독!! 역시 글 잘쓰시네요😊😊
사소한 몇 가지 리뷰남겨드립니다!!!
피드백이 늦어서 죄송해요😭

2020-06-07 15:27 UTC, kimevanjunseok commented on README.md
> +## 배경
보스독은 블로거이시니까!! 맞춤법 리뷰합니다!!😊😊
이부분 맞춤법 검사기 돌려보는 것도 좋은 것 같아요!!!
맞춤법으로도 글의 신뢰도를 판단한다고도 하잖아요!!
보스독 싫어해서 그러는거 아닌거 알죠...?...헷😘

2020-06-07 15:27 UTC, kimevanjunseok commented on README.md
> +- 결제 기능을 추가한다면, 베스트 댓글을  열람할 수 있는 구독 서비스를 붙인다거나, 열람하는 댓글 수만큼 포인트를 차감하는 식도 생각해 볼 수 있을 것입니다.
오...벌이까지 생각하시는 당신은...보스독...👍

2020-06-07 15:27 UTC, kimevanjunseok commented on README.md
> +이 서비스의 핵심기능은 기업정보(면접 질문 출처)를 공개하지 않고, 누군가 궁금한 혹은 직접 경험한 면접 질문을 게시한다면, 다른 사용자들이 해당 질문에 대해 자신이 생각한 모범 답안을 답안(댓글)로 작성합니다. 좋아요를 많이 받은 답안(댓글)순으로 답안(댓글)이 정렬되는 것이 기본적으로 제공되는 기능입니다.
기업정보를 공개하지 않는 이유가 있나요??
면접 질문이 같아도 기업의 인재상에 따라 대답이 달라질 수 있고, 
반도체 회사와 웹 서비스 회사는 똑같이 코딩을 하지만 이것 또한 대답이 달라질 수 있다고 생각합니다.
그러면 나에게 맞는 질문을 찾기 힘들 것 같다는 생각이 듭니다😭

2020-06-07 15:54 UTC, jnsorn commented on README.md
> +이 서비스의 핵심기능은 기업정보(면접 질문 출처)를 공개하지 않고, 누군가 궁금한 혹은 직접 경험한 면접 질문을 게시한다면, 다른 사용자들이 해당 질문에 대해 자신이 생각한 모범 답안을 답안(댓글)로 작성합니다. 좋아요를 많이 받은 답안(댓글)순으로 답안(댓글)이 정렬되는 것이 기본적으로 제공되는 기능입니다.
지나가던 사람이지만 유추해본다면, 대부분의 면접내용이 유출금지기 때문에 기업 정보를 비공개로 한 것이지 않을까 생각합니다.....🤔
다만 티거의 말도 맞다고 생각해서, 밝힐 수 있는 기업에 대해서는 밝히는 쪽이 사용자들에게 훨씬 도움이 될 것 같다고 생각이 드네요😃

2020-06-07 16:10 UTC, jnsorn approved these changes
안녕하세요! 보스독🐕 리뷰를 맡게 된 또링이에요! 처음 기획안을 읽어보고 참신하다고 생각했는데, 비슷한 서비스가 이미 존재했네요. 보스독이 말씀하신대로 본 서비스만의 차별성을 갖게 된다면 아주 유용한 서비스가 될 것 같아요!

개인적으로 시나리오가 구성요소(맥락, 니즈, 계기)가 적절하게 잘 들어가있어서 그런지 납득도 잘 가고 공감이 됐어요😛👍

의문점이나 제안드리고 싶은 부분에 대해 코멘트 드렸으니 확인 부탁드릴게요!ㅎㅎ

2020-06-07 16:10 UTC, jnsorn commented on README.md
> +#### 시나리오
시나리오가 매우 구체적이고 맥락, 니즈, 계기가 모두 확실하네요! 정말 공감가고 현실적인 시나리오입니다😊

2020-06-07 16:10 UTC, jnsorn commented on README.md
> +| "질문페이지를 북마크할 수 있는 기능이 있었다."               | 질문을 북마크처리하면 마이페이지에 등록되고 북마크 목록만 따로 볼 수 있어야 한다. |
북마크 된 질문이 많아질수록 나중에 찾아볼 때 어려움이 있을 것 같아요! 실제 크롬 북마크같이 폴더별로 나눌 수 있는 기능이 있으면 더욱 질문을 찾기 수월해질 것 같다는 생각이 드네요!🙂

2020-06-07 16:10 UTC, jnsorn commented on README.md
> +2019년 5월 통계청 자료에 의하면 취업 준비생은 71만명에 달합니다. 갈수록 늘어나는 취업난에 취준생들은 좋은 일자리를 얻기위해서 열심히 시험을 준비하고 또 면접을 준비합니다. 분야를 막론하고, "사람"을 뽑는 채용에서 빠질수 없는 부분이 바로 "면접"입니다.
서비스 기획 배경이 확실하고 신뢰가는 내용이네요👍

2020-06-07 16:10 UTC, jnsorn commented on README.md
> +면접 "질문"과 "답변"을 집단 지성을 통해 쌓아가며 공유하는 서비스
이 서비스의 사용자는 누가 될까요? 위 설명만 보고 직군에 관계 없이 모든 취준생이 이용할 수 있을 거라 생각했는데, 아래 예시들을 보니 개발직군에 대한 얘기밖에 없어서 살짝 헷갈리네요!
만약 모든 직군에 대한 서비스라면 질문에 직군을 표시하는 라벨정도는 붙일 수 있을 것 같아요!
아래 티거가 말한대로 회사/직군에 따라 같은 질문이어도 원하는 대답이 다를테니까요😏

2020-06-08 03:15 UTC, yeonnseok commented on README.md
> +이 서비스의 핵심기능은 기업정보(면접 질문 출처)를 공개하지 않고, 누군가 궁금한 혹은 직접 경험한 면접 질문을 게시한다면, 다른 사용자들이 해당 질문에 대해 자신이 생각한 모범 답안을 답안(댓글)로 작성합니다. 좋아요를 많이 받은 답안(댓글)순으로 답안(댓글)이 정렬되는 것이 기본적으로 제공되는 기능입니다.
넵 저는 기업정보를 공개했을 때 예상되는 문제점도 무시할 수 없다고 생각해요
그리고 보통 취준생들은 취업 시즌이 정해져 있다보니 한번에 관심분야의 여러 기업들을 지원하지 않을까요? (저도 그렇구요 ㅎㅎ)

물론 구체적인 기업정보가 있다면 이용자입장에서는 정보가 더생기는 것이니 좋겠지만, 어차피 그 기업 기출면접질문만 대비하는 사람은 드물것이고, 직무관련 질문들을 모아보는 것만으로도 서비스가 제공할 수 있는 가치는 충분할 것이라고 생각합니다!

혹시 티거는 한 기업만 바라보는 스타일이신건가요?ㅎㅎ

2020-06-08 03:16 UTC, yeonnseok commented on README.md
> +#### 시나리오
긴 시나리온데 잘 읽어주셔서 감사합니다! ㅎㅎ

2020-06-08 03:17 UTC, yeonnseok commented on README.md
> +| "질문페이지를 북마크할 수 있는 기능이 있었다."               | 질문을 북마크처리하면 마이페이지에 등록되고 북마크 목록만 따로 볼 수 있어야 한다. |
북마크 페이지 역시 태그로 분류하는 기능은 생각해보고 있었는데
폴더를 두는 것도 괜찮은 방향이네요! 조언 감사드립니다 또링 ㅎㅎ

2020-06-08 03:17 UTC, yeonnseok commented on README.md
> +2019년 5월 통계청 자료에 의하면 취업 준비생은 71만명에 달합니다. 갈수록 늘어나는 취업난에 취준생들은 좋은 일자리를 얻기위해서 열심히 시험을 준비하고 또 면접을 준비합니다. 분야를 막론하고, "사람"을 뽑는 채용에서 빠질수 없는 부분이 바로 "면접"입니다.
감사합니다 ㅎㅎㅎ

2020-06-08 03:26 UTC, yeonnseok commented on README.md
> +면접 "질문"과 "답변"을 집단 지성을 통해 쌓아가며 공유하는 서비스
터틀이 피드백 준 내용과 더불어서 서비스의 초기 시장 스콮은 좁게 시작할 것 같아요.
(아직은 확정되지않았지만요! 추후 논의가 진행되면 정해보려고해요! 개발직군을 대상으로 할수도 있고 모든 직군에 대한 질문으로도 시작할 수 있겠죠?)

넵 그리고 기획서에는 아직 수정반영하지 못했지만,
태그를 통해서 "#IT기업", "#백엔드", "#플랫폼 관리" 이런식으로 질문의 검색 경로를 좁히려고합니다.
(개발분야가 아니라면, "#물류기업", "#마케팅" 이런식으로도 확장가능하겠죠?)

또링이 말씀해주신 라벨도 괜찮은 방법이네요! 태그와 라벨을 적절히 섞어서 괜찮은 모델로 발전시켜보면 좋을 것 같네요! 섬세한 피드백 감사드립니다 :)

질문 첫부분에 서비스의 사용자에 대해서 물어봐주셨는데 현재는 취업준비생을 대상으로 서비스를 기획하고 있지만, ver2, ver3는 취업면접을 넘어서, 알바면접, 동아리 면접, 대학원 면접 등 여러 분야로 확장가능하다는 것을 말씀드리고 싶네요 :)🤗

2020-06-08 04:29 UTC, yeonnseok commented
리뷰어 여러분 모두 좋은 피드백 감사드립니다.
급하게 생각한 아이디어라 부족한 점이 많았네요
리뷰주신 부분들 모두 고려해서 아이디어를 더 구체화하고 최종 기획서에 반영해보도록할게요!
감사합니다!!

2020-06-09 08:08 UTC, gracefulBrown requested changes
안녕하세요 보스독! 글 잘읽어보았습니다!
이 아이디어의 핵심은 얼마나 많은 컨텐츠 제작자가 참여 하는지와 
얼마나 퀄리티 있는 답변, 신뢰가 있는 답변을 남기는지에 있는 것 같네요!

글을 소비하는 사람의 유저 시나리오도 잘 써주셨듯이
글을 생산하는 사람들의 니즈와 시나리오를 구체적으로 표현해보세요^^

2020-06-09 22:43 UTC, gracefulBrown approved these changes
피드백 반영확인했어요ㅎㅎ
질문에 대한 답변을 등록하는 행위를 이끌어내는게 쉽지 않을 수 있을 것 같아서
커뮤니티 활동을 활발하게 하는 요소가 무엇인지 고민해보았으면 했어요ㅎㅎ
여러 케이스에 대한 요구사항을 바탕으로 기획서 마무리 잘 하시길 바랄게요^^

2020-06-09 22:43 UTC, merged