[로운] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #8
Opened 2020-06-04 06:37 UTC by lowoon

[여기](https://github.com/lowoon/woowa-userstory-2020/tree/lowoon)를 참조하세요!

2020-06-04 07:29 UTC, woonjangahn approved these changes
안녕하세요 로운!
요구사항에 맞게 잘 작성해주셨어요 💯 💯 

학습용으로나 취미용으로나 학원을 알아볼 때 불편한 점들이 많았는데, 이를 해소할 수 있는 측면에서 좋은 기획인 것 같습니다.

[강남엄마](https://www.gangmom.kr/)와 유사한 느낌이 드는데, 참고해서 차별점을 만드시면 더 좋을 것 같네요. 대치동 등 학원가에서는 오프라인 교육을 듣기 위해 학원 대기 예약을 하는 경우가 굉장히 많았는데, 이에 대해서도 혹시 수강신청 같은 솔루션을 만들 수 있다면 좋을 것 같습니다.

전반적으로 봤을 때 우선 데이터 수집이 제일 중요할 것 같네요. 정부 데이터 포탈 등에서 제공하지 않는 정보이고 인강을 제외한 오프라인 강의는 강의료가 비공개인 곳도 많으니 학원들과 제휴를 맺기에 앞서 데이터를 수집해서 합법적으로 사용할 수 있는지에 대한 조사 역시 필요할 것 같습니다.

고생하셨습니다! 기대할게요 :)

2020-06-05 04:57 UTC, KueNiYam approved these changes
안녕하세요, 로운! 그니입니다. :) 
강의나 학원을 선택할 때 그에 대한 평점이나 리뷰를 확인할 방법이 없어서 입소문으로만 판단했던 것을 생각해보면 괜찮은 기획인 것 같아요. 약간 대학교 강의평가 같은 느낌도 있고요.

하지만 결제 시스템은 학원과 제휴를 맺어야 한다는 점에서 어려움이 있는 것 같아요. 이미 여러 학원이 자사의 인강 웹 서비스를 가지고 있기도 하고요. 
오프라인 학원의 경우에는 학원에서 직접 상담을 하고 결제 하는 경우가 많기 때문에 결제 대행 서비스를 사용할 지 의문이 생기기도 합니다.

한 가지 생각이 떠올랐는데요, 개인 과외와 고객을 이어주는 서비스를 추가하는 것도 괜찮을 것 같아요. 과외 선생님의 시간표를 공유하고 이에 맞추어 신청할 수 있도록이요!

2020-06-07 15:30 UTC, KS-KIM approved these changes
안녕하세요 로운, 알트입니다! 미션 잘 작성하셨어요 👍👍 
간단한 피드백 남겼으니 확인해보시고 궁금한 점 있으시면 DM 주세요!

> 홍보인지 실제 추천인지 알 수 없고, 어떤 강의를 들어야 할지도 몰라 포기함

리뷰가 핵심 컨텐츠인만큼 알바를 고용해서 조직적으로 어뷰징 하는것에 대한 대처법을 강구해 볼 필요가 있을 것 같아요. 해당 학원(또는 플랫폼)과 제휴를 맺지 않은 이상 리뷰어가 진짜로 경험을 하고 쓴 글인지 판단하기 어려울 것 같거든요. 제휴를 하더라도 여론조작을 위해 허위 결제를 하여 리뷰의 신뢰성을 깨트리는 일이 발생할 수도 있을 것 같은데, 이를 해결할 수 있는 아이디어가 있다면 좋은 플랫폼으로 성장할 수 있을 것 같아요.

맞춤법 피드백은 확인해보시고 고칠 필요성을 느끼시면 반영해주세요.
고생하셨습니다! 이만 Approve 할게요😊

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +- 취미로 새로운 것은 배우려고 할 때, 기본적으로 교육의 퀄리티가 아닌 집에서 가까운 곳 혹은 홍보글을 통해
```suggestion
- 취미로 새로운 것은 배우려고 할 때, 기본적으로 교육의 퀄리티가 아닌 집에서 가까운 곳 혹은 홍보 글을 통해
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +- 대부분 주변 사람들이 추천해주는 곳으로 찾아가고, 주변에 해본 사람이 없는 경우에는 직접 경험해 볼 수 밖에 없다.
```suggestion
- 대부분 주변 사람들이 추천해주는 곳으로 찾아가고, 주변에 해본 사람이 없는 경우에는 직접 경험해 볼 수밖에 없다.
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +    - 평가를 할 경우, 포인트를 얻을 수 있다.
```suggestion
    - 평가할 경우, 포인트를 얻을 수 있다.
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +    - 카드와 현금 뿐만 아니라 포인트를 이용해 듣고 싶은 강의를 결제할 수 있다.
```suggestion
    - 카드와 현금뿐만 아니라 포인트를 이용해 듣고 싶은 강의를 결제할 수 있다.
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +    - 데이터가 많이 쌓인 경우 강의를 수강한 사람들의 평가만 반영되도록 수정한다.
```suggestion
    - 데이터가 많이 쌓이면 강의를 수강한 사람들의 평가만 반영되도록 수정한다.
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +- 학업을 위해 오프라인 학원을 찾는 중,고등학생
```suggestion
- 학업을 위해 오프라인 학원을 찾는 중, 고등학생
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +- 커리큘럼이 제대로 짜여져 있는 강의를 듣고 싶다. (흥미와 수준 고려)
```suggestion
- 커리큘럼이 제대로 짜여 있는 강의를 듣고 싶다. (흥미와 수준 고려)
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +- 강의들을 카테고리 별로 분류한다.
```suggestion
- 강의들을 카테고리별로 분류한다.
```

2020-06-07 15:30 UTC, KS-KIM commented on README.md
> +- 강의에 대한 기본적인 정보(가격, 강사, 커리큘럼)을 확인할 수 있어야 한다.
```suggestion
- 강의에 대한 기본적인 정보(가격, 강사, 커리큘럼)를 확인할 수 있어야 한다.
```

2020-06-08 00:59 UTC, YejiAhn approved these changes
안녕하세요, 로운! 기획서 잘 읽어보았어요 😊
특정 분야를 공부하고 싶을 때 어떤 강의를 들어야 좋을지 잘 알 수가 없었는데, 사용자의 답답한 부분을 잘 해소해줄 것 같은 플랫폼이네요!
기획서를 읽고 굉장히 규모가 큰 서비스가 될 것 같다는 생각을 했는데요, 일단 연령대 제한이 없고(성인용 강의/중고등학생용 강의), 강의 기반 제한도 없고(온라인/오프라인), 기능도 굉장히 다양해요(평가/결제/홍보/수강신청 등).
8주짜리 프로젝트의 기획서이니만큼 목표로 하는 서비스의 제일 핵심이 되는 기능을 조금 더 명확히 추려주면 어떨까 하는 생각이 들었어요. 그러면 사용자 유입도 더 쉬워질 것 같아요.
그밖에 첨언할 말은 없습니다! 이만 approve할게요 수고하셨습니다 : )

2020-06-09 05:08 UTC, gracefulBrown requested changes
안녕하세요 로운~ 기획서 잘 봤습니다!
기획동기와 타겟 고객이 명확하고 이해가 잘 되었어요.

시나리오와 요구사항도 잘 작성해주셨는데요
강의를 등록하기 위한 시나리오도 필요할 것 같아요.
현재 기획서로는 강의 등록을 운영자가 하는지 아니면 사용자가 직접하는지 알 수가 없네요ㅠ
운영자들이 직접 강의를 올린다면 이 서비스의 확장성에 한계가 있을 것 같고
사용자들로 하여금 올리게 한다면 이 부분에 대한 시나리오도 필요할 것 같네요 :)
한번 고려해보시면 좋을 것 같습니다!

2020-06-09 09:42 UTC, gracefulBrown approved these changes
피드백 반영 잘 해주셨어요!
조금더 명확해져서 좋아진거 같아요 :)
마지막 피드백때 조금 더 구체적인 피드백 드리도록 할게요~

2020-06-09 09:42 UTC, merged