[오구] 사용자 이야기 미션 제출합니다.
woowacourse/woowa-userstory-2020 pull request #9
Opened 2020-06-04 06:41 UTC by LTTTTTE

2020-06-05 07:33 UTC, DunDung approved these changes
sns는 글과 사진으로 이루어진 것이 당연하다.라고 생각했었는데
음성 위주의 sns라니 혁신적인 아이디어 같아요.
게시글과 그 댓글들에서 음성을 듣는것은 글을 읽는 것보다 시간을 오래 써야하기 때문에 무조건 음성보다는 음성을 주로하는 분위기에 글도 허용하는 서비스였으면 좋겠어요!

2020-06-05 07:33 UTC, DunDung commented on README.md
> +- 그러나 모든 프로필과 글이 음성으로 되어있다.
음성과 사진을 제외한 글을 적는건 금지되는 건가요!?

2020-06-05 07:51 UTC, pci2676 approved these changes
음성기반의 SNS는 처음보는것 같아요! 재미있는 기획이네요!
실제로 중화권은 채팅보다 음성메세지를 많이쓴다고하니 좋은 서비스가 될수 있을것 같아요!

2020-06-05 11:17 UTC, jjj0611 approved these changes
점점 더 글보다 영상 기반 플랫폼이 익숙해져 가서 좋은 기획인 것 같아요.
소비하기 편하고 생산하기도 편한 SNS라 이용하기엔 편할 것 같은데,
스마트폰의 특성상 시각적 요소가 아예 없으면 좀 어색할 것 같기도 하네요!
기획 잘 봤습니다 :)

2020-06-05 11:17 UTC, jjj0611 commented on README.md
> +- 일상 공유, 자유 토론, 신세한탄 등을 할 수 있는 global chat 공간이 있고,
global chat 공간은 한 글에 대해 thread를 팔 수 있는 방식인가요?(일종의 댓글)
그냥 글을 막 올리게 되는 공간인가요?

2020-06-05 11:17 UTC, jjj0611 commented on README.md
> +재미있는 사용자의 게시물에 좋아요를 눌렀다. 그리고 금주의 좋아요 순위를 각 테마 탭 별로 볼 수 있었다.
여러 테마들을 만들고, 시기와 유행에 맞게 테마를 추가하면 좋을 것 같아요 👍

2020-06-05 11:17 UTC, jjj0611 commented on README.md
> +여러 답글이 달린 게시물을 발견하고 답글 전체읽기 버튼을 통해 전체 답글을 한번에 들었다.
인스타 스토리 방식처럼 클릭하여 넘길 수 있으면 더 좋을 것 같아요 😄

2020-06-06 06:36 UTC, hotheadfactory approved these changes
음성 SNS라니 신선한 컨셉인것 같아요:)
Approve 하겠습니다!

2020-06-06 06:36 UTC, hotheadfactory commented on README.md
> +재미있는 사용자의 게시물에 좋아요를 눌렀다. 그리고 금주의 좋아요 순위를 각 테마 탭 별로 볼 수 있었다.
음성만의 특징을 잘 살린 아이디어네요 👍

2020-06-06 06:36 UTC, hotheadfactory commented on README.md
> +- 일반적인 익명 커뮤니티 모바일 사이트 와 유사하다.
무조건 익명인 건가요? 아니면 기명으로 쓸 수 있는 게시판과 익명 게시판이 나누어져 있나요?
밑에는 프로필이 음성으로 되어있다고 되어 있는데 후자인가요?

2020-06-06 06:36 UTC, hotheadfactory commented on README.md
> +- 일상 공유, 자유 토론, 신세한탄 등을 할 수 있는 global chat 공간이 있고,
global chat은 실시간 채팅인가요? 아니면 자신의 음성파일을 피드에 올리는 공간인가요?

2020-06-06 07:39 UTC, LTTTTTE commented on README.md
> +- 그러나 모든 프로필과 글이 음성으로 되어있다.
글은 적을수 없습니다.
서비스 컨셉입니다.

2020-06-06 07:42 UTC, LTTTTTE commented on README.md
> +- 일상 공유, 자유 토론, 신세한탄 등을 할 수 있는 global chat 공간이 있고,
slack 전체잡담방이랑 동일하다고 생각하시면 됩니다.
올리는 글도 음성이고 thread(댓글)도 음성입니다.

2020-06-06 07:47 UTC, LTTTTTE commented on README.md
> +- 일반적인 익명 커뮤니티 모바일 사이트 와 유사하다.
기본 익명입니다.
에브리타임처럼 익명,프로필공유 두방법으로 게시할수 있습니다.

2020-06-08 01:10 UTC, jjj0611 commented
오구~ 어제 유튜브 광고보다가 봤는데
`탄탄`이라는 앱이 있더라구요.
이건 약간 데이팅 앱이긴한데 음성기반이라 참고해보면 좋지 않을까 해서 코멘트 남겼어요~

2020-06-09 08:16 UTC, gracefulBrown requested changes
안녕하세요 오구 !
참신한 아이디어 잘 읽어보았습니다.
활성화가 되면 정말 많은 사용자들이 이용할것 같은데요~
몇가지 궁금한점과 이견을 남겨보게요!

우선 시나리오 작성을 컨텐츠 소비자 입장에서 시나리오를 작성해주셨는데요
저는 초반에 이 서비스에서 가장 중요한 대상은 컨텐츠를 생산하고
자신의 이야기를 업로드하는 컨텐츠 생산자가 아닐까 생각됩니다.
그들의 입장에서 시나리오와 요구사항을 정리해 보면 어떨까요?

2020-06-10 06:51 UTC, LTTTTTE commented
컨텐츠 소비자가 곧 컨텐츠 생산자라 생각하고 시나리오를 작성하였습니다.
제 서비스에서 오직 컨텐츠를 생산만 하는 사람은 존재하지 않을 것이라 생각합니다.
서비스 극 초반에 컨텐츠 생산자에서 문제가 발생할것 같은데, 이때 컨텐츠를 생산하게할 마땅한 동기 부여가 없습니다.
그래서 극 초반에는 지인들의 도움을 빌려서 기본 적으로 다른 사용자들이 보고 재밌어 할 수 있는 컨텐츠를 생산해낼 계획입니다.

2020-06-10 20:47 UTC, gracefulBrown approved these changes
생산자가 즉 소비자가 되는 시나리오가 가장 이상적이겠네요 :)
하지만 아마도 생산과 소비를 같이 하는 사람 보다 소비만 하는 비율이 늘어날 수 있는데요
이 문제를 잘 해결한다면 좋은 서비스가 될 것 같아요!ㅎㅎ
최종 기획서에서 구체적인 내용을 보충한다면 재밌는 서비스가 나올 것 같습니다. 👍

2020-06-10 20:48 UTC, merged